
<script type="text/javascript">
dojo.addOnLoad(function() {
	dijit.byId('field2').focus();	
	dijit.byId('field5').set('value','');
	dijit.byId('field5').set('placeHolder','Select');
	dijit.byId('field8').set('value','');
	dijit.byId('field8').set('placeHolder','Select');
	dijit.byId('field20').set('value','');
	dijit.byId('field20').set('placeHolder','Select');
});

function fnGetColgDeptList(IdCollege){ 
	if(IdCollege != "")
		{ 
			var xhrArgs = {
					url: "<?php echo $this->baseUrl();?>"+"/generalsetup/subjectsoffered/getcolgdeptlist/IdCollege/"+IdCollege,
					handleAs:'json',
					load:function(data){ 
						AutoFillNextEditableDropDown("field20",data); 
					}
			   }
			dojo.xhrGet(xhrArgs); 
		} 
	} 	
function AutoFillNextEditableDropDown(EditableDropDownId,JSONText){
	dijit.byId(EditableDropDownId).setValue("");
	var ddwidget = dijit.byId(EditableDropDownId);
	ddwidget.setAttribute('disabled', false);
	var options = {
				label:"name",
				identifier:"key",
				items:JSONText
			  };
	ddwidget.store = new dojo.data.ItemFileReadStore( { data: options } );
}	
</script>

	<fieldset>
		<legend><?php echo $this->translate("$this->Subject").' '.$this->translate("Search");?></legend>
         <form action="" method="POST">
            <table width="100%">
            	 <tr>
                   <td><?php echo $this->translate("$this->College").' '.$this->translate("Name");?></td>
                   <td ><?php echo $this->lobjform->field5;?></td>
                   <td><?php echo $this->translate("Branch").' '.$this->translate("Name");?></td>
                   <td ><?php echo $this->lobjform->field8;?></td>
                </tr>
                <tr>
                   <td><?php echo $this->translate("$this->Department").' '.$this->translate("Name");?></td>
                   <td ><?php echo $this->lobjform->field20;?></td>
                   <td><?php echo $this->translate("$this->Subject").' '.$this->translate("Name");?></td>
                   <td ><?php echo $this->lobjform->field2;?></td>
                </tr>
                <tr>
                   <td><?php echo $this->translate("$this->Subject").' '.$this->translate("Code");?></td>
                   <td ><?php echo $this->lobjform->field3;?></td>
                   <td><?php echo $this->defaultlanguage;?></td>
                   <td ><?php echo $this->lobjform->field4;?></td>
                </tr>
                <tr>                 
                   <td ><?php echo $this->translate("Active");?></td>
                   <td ><?php echo $this->lobjform->field7;?></td>
                   <td></td>
                   <td></td>
                </tr>
                <tr>
	               <td align = "center" colspan = "4">
						<?php echo $this->lobjform->Search;?>
						
						<?php echo $this->lobjform->Clear;?>
				   </td>
                </tr>
            </table>
        </form>	
    </fieldset> 
    <br/>
	<fieldset>
		<table class="table" width="100%" cellpadding="5" cellspacing="1">
		
	    	<tr>
	        	<th><?php echo $this->translate("$this->Subject Name");?></th>
	       	    <th><?php echo $this->defaultlanguage;?></th>
	       	    <th><?php echo $this->translate("Course").' '.$this->translate("Type");?></th>
	       	    <th><?php echo $this->translate("$this->Department").' '.$this->translate("Name");?></th>
	       	    <th><?php echo $this->translate("Branch").' '.$this->translate("Name");?></th>
	       	    <th><?php echo $this->translate("$this->College").' '.$this->translate("Name");?></th>
  				<th><?php echo $this->translate("Credit").' '.$this->translate("Hours");?></th>
	       </tr>
	        <?php if (count($this->paginator)): ?>
	        <?php foreach ($this->paginator as $lobjsubject ): ?>
	  		<tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next()?>">
	        	<td><a href="<?php echo $this->url(array('module'=>'generalsetup','controller'=>'subjectequivalent', 'action'=>'newsubjectequivalent' , 'id'=>$lobjsubject['IdSubject'],'code'=>$lobjsubject['SubCode'],'name'=>$lobjsubject['SubjectName']),'default',true);?>" ><?php print_r(' - '.$this->escape($lobjsubject['SubCode']).print_r($this->escape($lobjsubject['SubjectName'])));?></a></td>
	    	    <td><?php echo ($this->escape($lobjsubject['BahasaIndonesia'].' - '.$lobjsubject['SubCode']));?></td>
	    	    <td><?php echo $this->escape($lobjsubject['CourseName']);?></td>
	    	    <td><?php echo $this->escape($lobjsubject['DepartmentName']);?></td>
	    	    <td><?php if($lobjsubject['DepartmentType']==0) { echo "--"; }else{ echo $this->escape($lobjsubject['BranchName']); }?></td>
	    	 	<td><?php if($lobjsubject['DepartmentType']==0) { echo $this->escape($lobjsubject['BranchName']); }else{ echo $this->escape($lobjsubject['CollegeName']); }?></td>
	    	 	    <td><?php echo $this->escape($lobjsubject['CreditHours']);?></td>
	    	  <?php endforeach; ?>
	            <?php endif; ?> 
			</tr>
	    	<tr>
	        	<td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->lobjpaginator,'Sliding',
	                                    '/partials/my_pagination_control.phtml'); ?></div></td>
   			</tr>
		</table>
	</fieldset>
