<script>
function showAddDrop(){
	var LandscapeType = $('select[name="LandscapeType"]').val();
	
	if(LandscapeType==44){
		$("#AddDrop").attr( "disabled", "disabled" );
		$("#Blockcount").removeAttr( "disabled");	
		$("#Blockcount").attr( "required");	
		
	}else{
		$("#AddDrop").removeAttr( "disabled");			
		$("#Blockcount").attr( "disabled", "disabled" );
		$('#Blockcount').val(0);	
	}
}
</script>
<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>	
		   <li>
				<a href="<?php echo $this->url(array('module'=>'generalsetup','controller'=>'landscape', 'action'=>'landscape-list','id'=>$this->programId),'default',true); ?>">
					<span class='back'></span>
					Back
				</a>
			</li>		
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>

<br>

<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>

<br>

<div style="width:100%;">

<?php echo $this->form;?>

</div>