<script type="text/javascript">
var ProgramCreditHours = <?php echo $this->programcredit ?>;
var PRCreditH = 0;
var TotalSubHours = 0;
var PRCreditH = 0;
var LSubCreditH = new Array();
var PRSubCreditH = new Array();
var BalanceHours = new Array();
var AddHours = new Array();
var trs = 0;

var objArray = new Array();
var jsonObj = new Array();
var courseTypeArray = new Array();

var courseDataAndTypeArray = new Array();


var rowid = 1;
var rowid1 = 1;
var rowid2 = 1;
var rowid3 = 1;
	dojo.addOnLoad(function() {
		dijit.byId('IdStartSemester').set('value','');
		dijit.byId('IdStartSemester').set('placeHolder','Select');
		dijit.byId('IdSubject').set('value','');
		dijit.byId('IdSubject').set('placeHolder','Select');

	});

	//SHOWING PROGRAMREQUIREMENT
	function showprogreq() {
		var flag = true;
		var IdStartSemester = dijit.byId("IdStartSemester");
		if(IdStartSemester.get('value')== "") {
			IdStartSemester.set('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}
		if(flag == true) {
			dojo.byId("prgreq").style.display = "block";
			ProgramCreditHours = dijit.byId("TotalCreditHours").value;
			dojo.attr("TotalCreditHours", "readonly", true);
		}
		return flag;
	}

	function addLandscapeDetails() {
		var flag = true;
		if(dijit.byId("SubjectType")==''){
		    dijit.byId("SubjectType").attr('required','true');
			dijit.byId("SubjectType").focus();flag = false;
		}

		var SubjectType = dijit.byId("SubjectType");
		if(SubjectType.get('value')== "")
		{
			SubjectType.set('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}

		if(!dijit.byId("CreditHours").isValid()){
			dijit.byId("CreditHours").focus();
			flag = false;
		}

		if(dijit.byId("CreditHours").value==''){
		    dijit.byId("CreditHours").attr('required','true');
			dijit.byId("CreditHours").focus();flag = false;
		}

		if(flag == true) {
			podetailsInsert();
		}
		return flag;
	}

	var batchArray  = new Array();
	var addsubArray  = new Array();
	var subjArray = new Array();

	function podetailsInsert() {
		var SubjectType = dijit.byId("SubjectType");
		var SubjectTypename = dijit.byId("SubjectType").displayedValue;
		var CreditHours = dijit.byId("CreditHours").value;
		PRCreditH = parseFloat(PRCreditH) + parseFloat(CreditHours);

		PRSubCreditH[SubjectType] = CreditHours;
		LSubCreditH[SubjectType] = 0;
		BalanceHours[SubjectType] = CreditHours;
		AddHours[SubjectType] = 0;

		//console.log(SubjectTypename);
		if(parseFloat(PRCreditH) <= parseFloat(ProgramCreditHours)) {
			batchArray.push(SubjectTypename);
			if(arrHasDupes(batchArray)) {
				batchArray = batchArray.unique();
				PRCreditH = parseFloat(PRCreditH) - parseFloat(CreditHours);
				alert("Duplicate Course Type");
			} else {
				var Balance = ProgramCreditHours - PRCreditH;
				dijit.byId("Balance").set('value',Balance);
				var trow=document.getElementById('horprg').insertRow(rowid);
				var tcol1=trow.insertCell(0);
				var tcol2=trow.insertCell(1);
				var tcol3=trow.insertCell(2);
				var tcol4=trow.insertCell(3);
				var tcol5=trow.insertCell(4);


				tcol1.innerHTML="<input type='hidden' value='"+SubjectType+"' name=SubjectTypegrid[]>"+SubjectTypename;
				tcol2.innerHTML="<input type='hidden' id = 'credit' value='"+CreditHours+"' name=CreditHoursgrid[]>"+CreditHours;
				tcol3.innerHTML="<input type='text' disabled='disabled' readonly = 'true' size = '2' style='background-color:#E5E5E5;'  id = 'id"+SubjectType+"' value='"+BalanceHours[SubjectType]+"' name=BalanceHoursgrid[]>";
				tcol4.innerHTML="<input type='text' disabled='disabled' readonly = 'true' size = '2' style='background-color:#E5E5E5;' id = 'ad"+SubjectType+"' value='0' name=AddHoursgrid[]>"
				tcol5.innerHTML="<a href='#' onClick='deleteRowprogram(this,"+CreditHours+","+Balance+","+SubjectType+"); return false;'><img src='<?php echo $this->baseUrl();?>/images/delete.png'  border=0 width='16' height='16'></a>";
				rowid++;
				courseTypeArray.push({key:SubjectType.value,name:SubjectTypename});

			}




		} else {

			PRCreditH = parseFloat(PRCreditH) - parseFloat(CreditHours);
			alert("Course Type Credit Hours Exceeds Program Credit Hours ");
		}



	}

	function deleteRowprogram(r,CrHr,Blc,SubjectType) {
		var dStat = confirm("Are you sure to delete?");
                var adHrs = 'ad'+SubjectType;
                var adHrsValue = document.getElementById(adHrs).value;
                //console.log(adHrsValue);
                if(adHrsValue=='0'){ 
                    if(dStat == true && adHrsValue=='0') {  
                                rowid--;
                                var i=r.parentNode.parentNode.rowIndex;
                                batchArray.splice(parseInt(i-1),1);
                                document.getElementById('horprg').deleteRow(i);
                                PRCreditH = parseFloat(PRCreditH) - parseFloat(CrHr);
                                var Balance = Blc + CrHr;
                                dijit.byId("Balance").set('value',Balance);
                        } else { }                        
                } else { 
                    alert("Can't Delete Course Type as it has Courses Associated with it.");    
                }
        }        

	function showtablesub() {
	   //  var LandscapeSubjectType = dijit.byId('LandscapeSubjectType');
		//console.log(courseTypeArray);
		AutoFillNextEditableDropDown("LandscapeSubjectType",courseTypeArray);

		//dijit.byId('LandscapeSubjectType').item.value('value', '49');
        //dojo.empty("LandscapeSubjectType");

     	//dijit.byId('LandscapeSubjectType').set("value", 49);
     	//var newitem = ({'key':100,'value':100});
     	//dijit.byId('LandscapeSubjectType').set("item", newitem);
		 //dijit.byId('LandscapeSubjectType').removeOption(dijit.byId('LandscapeSubjectType').getOptions());



		if(PRCreditH < PRCreditH)
		{
			alert("Course Type Total Credit Hours Should be Equal to Program Total Credit Hours");
		} else {
	        // alert(dijit.byId("SubjectTypegrid").value);
			var SemsterCount = dijit.byId('SemsterCount').value;
			dojo.byId("table2").style.display = "block";
			fnGetBlocksubList(SemsterCount);
			dojo.byId("tr2").style.display = "none";
			dijit.byId('IdSubject').set('value','');
			dijit.byId('IdSubject').set('placeHolder','Select');
			dijit.byId('LandscapeSubjectType').set('value','');
			dijit.byId('LandscapeSubjectType').set('placeHolder','Select');
	    }
	}

	function fnGetBlocksubList(Blockcount){
		if(Blockcount != "") {
			var xhrArgs = {
				url: "<?php echo $this->baseUrl();?>"+"/generalsetup/landscape/getblocklist/Blockcount/"+Blockcount,
				handleAs:'json',
				load:function(data){
					AutoFillNextEditableDropDown("IdSemester",data);
				}
			}
			dojo.xhrGet(xhrArgs);
		}
	}

	function AutoFillNextEditableDropDown(EditableDropDownId,JSONText){
                //alert(EditableDropDownId);
		dijit.byId(EditableDropDownId).setValue("");
		var ddwidget = dijit.byId(EditableDropDownId);
		ddwidget.setAttribute('disabled', false);
    	var options = {
			label:"name",
			identifier:"key",
			items:JSONText
		};
    	ddwidget.store = new dojo.data.ItemFileReadStore( { data: options } );
	}


	function fngetsubjectcredithours(idsubject) {
	if(idsubject != "") {
		var xhrArgs = {
			url: "<?php echo $this->baseUrl();?>"+"/generalsetup/landscape/fngetsubjectcredithours/idsubject/"+idsubject,
			handleAs:'text',
			load:function(data){
			dojo.byId('subcredithours').value = parseFloat(data);
			dojo.byId('chours').innerHTML = data;
		}
	}
	dojo.xhrPost(xhrArgs);
		}
	}





	function addLandscapeprogDetails() {
		var flag = true;
		if(dijit.byId("IdSubject")==''){
		    dijit.byId("IdSubject").attr('required','true');
			dijit.byId("IdSubject").focus();flag = false;
		}
		var IdSubject = dijit.byId("IdSubject");
		if(IdSubject.get('value')== "") {
			IdSubject.set('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}

		if(dijit.byId("IdSemester")==''){
		    dijit.byId("IdSemester").attr('required','true');
			dijit.byId("IdSemester").focus();flag = false;
		}
		var IdSemester = dijit.byId("IdSemester");
		if(IdSemester.get('value')== ""){
			IdSemester.set('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}

		if(dijit.byId("LandscapeSubjectType")==''){
		    dijit.byId("LandscapeSubjectType").attr('required','true');
			dijit.byId("LandscapeSubjectType").focus();flag = false;
		}

		var LandscapeSubjectType = dijit.byId("LandscapeSubjectType");
		if(LandscapeSubjectType.get('value')== "") {
			LandscapeSubjectType.set('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}

		if(flag == true) {
			LandscapeprogInsert();
		}
		return flag;
	}
	function LandscapeprogInsert()
	{
		var IdSemester = dijit.byId("IdSemester");
		var IdSemestername = dijit.byId("IdSemester").displayedValue;

		var Idmajor = dijit.byId("IdProgramMajoring");
		var majorname = dijit.byId("IdProgramMajoring").displayedValue;

		var IdSubject = dijit.byId("IdSubject");
		var IdSubjectname = dijit.byId("IdSubject").displayedValue;

		var LandscapeSubjectType = dijit.byId("LandscapeSubjectType");
		var LandscapeSubjectTypename = dijit.byId("LandscapeSubjectType").displayedValue;

		var SubjectCreditHours = 0;
		SubjectCreditHours = dojo.byId("subcredithours").value;

		//TotalSubHours = parseFloat(TotalSubHours) + parseFloat(SubjectCreditHours);
                //console.log(LSubCreditH[LandscapeSubjectType]);
		var count = 0;
		LSubCreditH[LandscapeSubjectType] = parseFloat(LSubCreditH[LandscapeSubjectType]) + parseFloat(SubjectCreditHours);

		//console.log(LSubCreditH[LandscapeSubjectType]);
                //console.log(PRSubCreditH[LandscapeSubjectType]);

			if(parseFloat(LSubCreditH[LandscapeSubjectType])  <= parseFloat(PRSubCreditH[LandscapeSubjectType]))
			{
				courseDataAndTypeArray.push(IdSubjectname+'#'+LandscapeSubjectTypename);
				//console.log(courseDataAndTypeArray);
                                if(arrHasDupes(courseDataAndTypeArray))
				{
					courseDataAndTypeArray = courseDataAndTypeArray.unique();
					dojo.byId('subcredithours').value = '';
					//dijit.byId('IdSemester').set('value','');
					//dijit.byId('IdSemester').set('placeHolder','Select');
					dijit.byId('IdSubject').set('value','');
					dijit.byId('IdSubject').set('placeHolder','Select');
					document.getElementById('chours').innerHTML = '';
                                        LSubCreditH[LandscapeSubjectType] = LSubCreditH[LandscapeSubjectType]- parseFloat(SubjectCreditHours);
					alert("Duplicate Course and Course Type");
				} else {
					//LSubCreditH[LandscapeSubjectType] =  parseFloat(SubjectCreditHours);
					//BalanceHourse = BalanceHours[LandscapeSubjectType] - LSubCreditH[LandscapeSubjectType];
					BalanceHourse = BalanceHours[LandscapeSubjectType] - parseFloat(SubjectCreditHours);
                                        BalanceHours[LandscapeSubjectType] = BalanceHourse;
					var idS = 'id'+LandscapeSubjectType;
					dojo.byId(idS).value = BalanceHours[LandscapeSubjectType];

					var tes = trs + parseFloat(SubjectCreditHours);
					AddHours[LandscapeSubjectType] = AddHours[LandscapeSubjectType] + tes;
					var ads = 'ad'+LandscapeSubjectType;
					dojo.byId(ads).value = AddHours[LandscapeSubjectType];

					//console.log(BalanceHours[LandscapeSubjectType]);
					//console.log(AddHours[LandscapeSubjectType]);

					var trow=document.getElementById('hor1').insertRow(rowid1);
					var tcol1=trow.insertCell(count);count++;
					var tcol2=trow.insertCell(count);count++;
					var tcol3=trow.insertCell(count);count++;
					var tcol4=trow.insertCell(count);count++;
					var tcol5=trow.insertCell(count);count++;
					var tcol6=trow.insertCell(count);count++;

					tcol1.innerHTML="<input type='hidden' value='"+IdSemester+"' name=IdSemestergrid[]>"+IdSemestername;
                                        tcol2.innerHTML="<input type='hidden' value='"+LandscapeSubjectType+"' name=LandscapeSubjectTypegrid[]>"+LandscapeSubjectTypename;
					tcol3.innerHTML="<input type='hidden' value='"+IdSubject+"' name=IdSubjectgrid[]>"+IdSubjectname;
					tcol4.innerHTML="<input type='hidden' value='"+Idmajor+"' name=IdProgramMajoringgrid[]>"+majorname;					
					tcol5.innerHTML="<input type='hidden' value='"+SubjectCreditHours+"' name=LandscapeCreditHoursgrid[]>"+SubjectCreditHours;
					tcol6.innerHTML='<a href="#" onClick="deleteRowsubject(this,'+LandscapeSubjectType+','+SubjectCreditHours+',\''+IdSubjectname+'\',\''+LandscapeSubjectTypename+'\'); return false;"><img src="<?php echo $this->baseUrl();?>/images/delete.png"  border=0 width=16 height=16></a>';
				        rowid1++;

					dojo.byId('subcredithours').value = '';
					//dijit.byId('IdSemester').set('value','');
					//dijit.byId('IdSemester').set('placeHolder','Select');
					dijit.byId('IdSubject').set('value','');
					dijit.byId('IdSubject').set('placeHolder','Select');
					document.getElementById('chours').innerHTML = '';
				}
		     }
			else
			{
				dojo.byId('subcredithours').value = '';
				//dijit.byId('IdSemester').set('value','');
				//dijit.byId('IdSemester').set('placeHolder','Select');
				dijit.byId('IdSubject').set('value','');
				dijit.byId('IdSubject').set('placeHolder','Select');
				document.getElementById('chours').innerHTML = '';
				alert("Course Credit Hours Exceeds Course Type Credit Hours ");
				LSubCreditH[LandscapeSubjectType] = LSubCreditH[LandscapeSubjectType]- parseFloat(SubjectCreditHours);
			}

	}


	function deleteRowsubject(r,LType,SubCrHr,IdSubjectname,LandscapeSubjectTypename) {          
               
		var dStat = confirm("Are you sure to delete?");
                if(dStat == true){
                                rowid1--;
                                var i=r.parentNode.parentNode.rowIndex;
                                //alert(i);
                                subjArray.splice(parseInt(i-1),1);
                                document.getElementById('hor1').deleteRow(i);
                                //LSubCreditH[LType] =  parseFloat(SubCrHr);
                                LSubCreditH[LType] = LSubCreditH[LType]- parseFloat(SubCrHr);
                                BalanceHourse = BalanceHours[LType] + parseFloat(SubCrHr);
                                BalanceHours[LType] = BalanceHourse;

                                var idS = 'id'+LType;
                                dojo.byId(idS).value = BalanceHours[LType];

                                var tes = trs + parseFloat(SubCrHr);
                                AddHours[LType] = AddHours[LType] - tes;
                                var ads = 'ad'+LType;
                                dojo.byId(ads).value = AddHours[LType];                                
                                
                                var makeArr = IdSubjectname+'#'+LandscapeSubjectTypename;
                                courseDataAndTypeArray.splice(courseDataAndTypeArray.indexOf(makeArr), 1);
                                
                                //console.log(BalanceHours[LType]);
                                //console.log(AddHours[LType]);
                                dojo.byId('subcredithours').value = '';
                                //dijit.byId('IdSemester').set('value','');
                                //dijit.byId('IdSemester').set('placeHolder','Select');
                                dijit.byId('IdSubject').set('value','');
                                dijit.byId('IdSubject').set('placeHolder','Select');
                                document.getElementById('chours').innerHTML = '';
                                //console.log(LSubCreditH[LType]);
                } else {

                }
	}



	function addBlockDetails() {
		var flag = true;

		var block = dijit.byId("block");
		if(block.get('value')== "")
		{
			block.set('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}

		if(dijit.byId("blockname").value == ''){
		    dijit.byId("blockname").attr('required','true');
			dijit.byId("blockname").focus();flag = false;
		}

		if(flag == true) {
			blocknameInsert();
		}
		return flag;
	}

	var blockArray  = new Array();

	function blocknameInsert() {
		var block = dijit.byId("block");
		var blocknameid = dijit.byId("block").displayedValue;
		var blockname = dijit.byId("blockname").value;
		blockArray.push(blocknameid);
		if(arrHasDupes(blockArray)) {
			blockArray = blockArray.unique();
			alert("Duplicate Level");
		} else {
			var trow=document.getElementById('hor5').insertRow(rowid3);
			var tcol1=trow.insertCell(0);
			var tcol2=trow.insertCell(1);
			var tcol3=trow.insertCell(2);

			tcol1.innerHTML="<input type='hidden'   value='"+block+"' name=blockgrid[]>"+blocknameid;
			tcol2.innerHTML="<input type='hidden'  value='"+blockname+"' name=blocknamegrid[]>"+blockname;
			tcol3.innerHTML="<a href='#' onClick='deletelevel(this); return false;'><img src='<?php echo $this->baseUrl();?>/images/delete.png'  border=0 width='16' height='16'></a>";
			rowid3++;

	}
	}





	function arrHasDupes( A ) {              // finds any duplicate array elements using the fewest possible comparison
		var i, j, n;
		n=A.length;   						// to ensure the fewest possible comparisons
		for (i=0; i<n; i++) {                // outer loop uses each item i at 0 through n
			for (j=i+1; j<n; j++) {          // inner loop only compares items j at i+1 to n
				if (A[i]==A[j]) return true;
			}
		}
		return false;
	}

	Array.prototype.unique = function () {
	    var r = new Array();
	    o:for(var i = 0, n = this.length; i < n; i++) {
	        for(var x = 0, y = r.length; x < y; x++) {
	        	if(r[x]==this[i]) {
	                	continue o;
	              }
	        }
	        r[r.length] = this[i];
	    }
	    return r;
	}

</script>

<fieldset>
	<legend><?php echo $this->translate($this->Landscape);?></legend>
    	<Form dojoType="dijit.form.Form"  id="myForm" action="" method="post"  name= "myForm">
         	<script type="dojo/method" event="onSubmit">
         			//dijit.byId('IdSubject').set('value','');
					//dijit.byId('IdSubject').set('placeHolder','Select');
					//dijit.byId("IdSubject").attr('required','false');
					//var IdSubject = dijit.byId("IdSubject").value;
                if (this.validate()) {
					if(dijit.byId('ProgramDescription').value == ''){
						alert("Please enter Landscape Description");
						dijit.byId("ProgramDescription").attr('required','true');
						dijit.byId("ProgramDescription").focus();
						return false;	
					}			
					return true;
                } else {
                    return false;
                }
			</script>
		<div>
        	<table class="table" width="100%" >
            	<tr>
	        		<th colspan = "4"><?php echo $this->translate("Semester-Based Landscape");?></th>
				</tr>

	    		<tr>
	    		    <td><?php echo $this->translate("Program Name");?></td>
	    			<td><?php echo $this->program;?></td>
	    			<td><?php echo $this->translate("Total")." ".$this->translate("Credit")." ".$this->translate("Hours");?></td>
	    			<td><?php echo $this->lobjlandscapeform->TotalCreditHours;?></td>

	    		</tr>
	    		<?php
				if($this->Scheme==1){?>
	    		<tr>
	    			<td><?php echo $this->translate("Scheme");?></td>
	    			<td><?php echo $this->lobjlandscapeform->Scheme;?></td>
	    			<td><?php echo $this->translate("Landscape Description");?><span class="reqMark">*</span></td>
	    			<td><?php echo $this->lobjlandscapeform->ProgramDescription;?></td>
	    		</tr>
	    		<?php } ?>
	    		<tr>
	    			<td><?php echo $this->translate("Add/Drop");?></td>
	    			<td><?php echo $this->lobjlandscapeform->AddDrop;?></td>
    				<?php
					if($this->Scheme==1){?>
					<td><?php echo $this->translate($this->defaultlanguage);?></td>
					<td ><?php echo $this->lobjlandscapeform->landscapeDefaultLanguage;?></td>
					<?php } ?>
	    			
	    		</tr>
                <tr>
                	<th colspan = "4"><?php echo $this->translate($this->Landscape).' '.$this->translate("Details");?></th>
                </tr>
                <tr>
                	<td><?php echo $this->translate($this->Landscape);?><span class="reqMark">*</span></td>
                    <td><?php echo $this->lobjlandscapeform->LandscapeType;?>
                        <?php echo $this->lobjlandscapeform->UpdDate;?>
                        <?php echo $this->lobjlandscapeform->UpdUser;?>
                         <?php echo $this->lobjlandscapeform->IdProgram;?></td>
                     <!--<td><?php echo $this->translate("No").' '.$this->translate("of").' '.$this->translate("Blocks");?></td>
                     <td><?php echo $this->lobjlandscapeform->Blockcount;?></td>
                -->
                	<td><?php echo $this->translate("Intake");?><span class="reqMark"></span></td>
                    <td><?php echo $this->lobjlandscapeform->IdStartSemester;?></td>
                </tr>
                <tr>

                    <td><?php echo $this->translate("No").' '.$this->translate("of").' '.$this->translate("Semester");?></td>
                    <td><?php echo $this->lobjlandscapeform->SemsterCount;?><?php echo $this->lobjlandscapeform->session_id;?></td>
               		<td><?php echo $this->translate("Active");?><span class="reqMark"></span></td>
                    <td><?php echo $this->lobjlandscapeform->Active;?></td>
                </tr>
                <tr>

                    <td></td>
                    <td></td>

                </tr>
                <tr id = "tr1">
                	<td colspan=4 align = "right"><?php echo $this->lobjlandscapeform->Add9;?></td>
                </tr>
 			</table>
	</div>
	<div id = "prgreq" style="display:none" >
    	<table class="table" width="100%" >
        	<tr>
           		<th colspan = "4"><?php echo $this->translate("Program").' '.$this->translate("Requirement");?></th>
            </tr>
            <tr>
            	<td><?php echo $this->translate("Subject");?> <?php echo $this->translate("Type");?><span class="reqMark"></span></td>
                <td><?php echo $this->lobjlandscapeform->SubjectType;?></td>
                <td><?php echo $this->translate("Balance");?></td>
                <td><?php echo $this->lobjlandscapeform->Balance;?></td>
             </tr>
             <tr>
             	<td><?php echo $this->translate("Credit");?> <?php echo $this->translate("Hours");?><span class="reqMark"></span></td>
                <td><?php echo $this->lobjlandscapeform->CreditHours;?></td>
                <td></td>
                <td></td>
             </tr>
             <tr>
             	<td colspan=4 align = "right"><?php echo $this->lobjlandscapeform->Add;?></td>
             </tr>
		</table>
        <table id="horprg"  class="table" width="100%" >
			<tr>
				<th><?php echo $this->translate->_("Subject").' '.$this->translate->_("Type")?></th>
				<th><?php echo $this->translate->_("Credit").' '.$this->translate->_("Hours")?></th>
				<th><?php echo $this->translate->_("Balance").' '.$this->translate->_("Hours")?></th>
				<th><?php echo $this->translate->_("Added").' '.$this->translate->_("Hours")?></th>
				<th><?php echo $this->translate->_("Delete")?></th>
			</tr>
			<tr>
            	<td colspan=5 id = "tr2" align = "right"><?php echo $this->lobjlandscapeform->Add7;?></td>
            </tr>
		</table>
	</div>
	<div id = "table2" style="display:none">
		<table class="table" width="100%" >
        	<tr>
           		<th colspan = "4"><?php echo $this->translate("Subject").' '.$this->translate("Details");?></th>
                </tr>
            <tr>
                 <td><?php echo $this->translate("Semester");?><span class="reqMark">*</span></td>
                 <td><?php echo $this->lobjlandscapeform->IdSemester;?></td>
                 <td><?php echo $this->translate("Subject").' '.$this->translate("Type");?><span class="reqMark">*</span></td>
                 <td><?php echo $this->lobjlandscapeform->LandscapeSubjectType;?></td>
            </tr>
            
             <tr>
                <td><?php echo $this->translate("Subject");?><span class="reqMark">*</span></td>
                <td><?php echo $this->lobjlandscapeform->IdSubject;?><input type="hidden" name="subcredithours" id="subcredithours" value="" /></td>
                <td><?php echo $this->translate("Majoring");?></td>
                <td><?php echo $this->lobjlandscapeform->IdProgramMajoring;?></td>            	
             </tr>             
                
	    <tr>				
                <td><?php echo $this->translate("Credit").' '.$this->translate("Hours");?></td>
                <td><span id='chours'></span></td>
                <td><?php echo $this->translate("Compulsory");?><span class="reqMark"></span></td>
                <td><?php echo $this->lobjlandscapeform->Compulsory;?></td>
            </tr>
            
           
           <tr>
          		<td colspan=4 align = "right"><?php echo $this->lobjlandscapeform->Add1;?><input type = "hidden" name = "IdProgramReq" value = "<?php echo $this->IdProgramReq;?>"/>
                </td>
           </tr>
       </table>
       <table id="hor1"  class="table" width="100%" >
			<tr>
				<th><?php echo $this->translate->_("Semester");?></th>
                                <th><?php echo $this->translate->_("Subject").' '.$this->translate->_("Type");?></th>
				<th><?php echo $this->translate->_("Subject");?></th>
				<th><?php echo $this->translate->_("Majoring");?></th>			        
				<th><?php echo $this->translate->_("Credit").' '.$this->translate->_("Hours");?></th>
				<th><?php echo $this->translate->_("Delete")?></th>
			</tr>
		</table>
	</div>
	<div id = "table4" >
		<table class="table" width="100%">
			<tr  align = "right">
            	<td><?php echo $this->lobjlandscapeform->Save;?></td>
             </tr>
		</table>
	</div>
	<div>
		<table class="table" width="100%">
			<tr  align = "right">
            	<td>
                	<input type="button" class="NormalBtn" dojotype="dijit.form.Button" label="<?php echo $this->translate("Back"); ?>" onclick="window.location.href='<?php echo $this->url(array('module'=>'generalsetup','controller'=>'landscape', 'action'=>'addlandscape','id'=>$this->IdProgram),'default',true);?>';" />
                 </td>
             </tr>
		</table>
	</div>

<!-- SEMESTER LANDSCAPE COPY   -->
	 <div>

	<table class="table" width="100%" >
            	<tr>
	        		<th colspan = "4"><?php echo $this->translate("Copy").' '.$this->translate("Landscape");?>
	        		<span id="targetCopy" style="color:red;display:none;margin-left: 405px;">Copying Data, Please Wait a While...</span>
	        		</th>
				</tr>


				<tr>
	    		    <td><?php echo $this->translate("Program Name");?></td>
	    			<td><?php echo $this->program;?></td>
	    			<td><?php echo $this->translate("Scheme");?></td>
	    			<td><?php echo $this->lobjlandscapeform->CopyScheme;?></td>
	    		</tr>
				<tr>
					<td><?php echo $this->translate("Intake");?></td>
					<td><?php echo $this->lobjlandscapeform->CopyIdStartSemester;?></td>
					<td><?php echo $this->translate("Active");?></td>
					<td><?php echo $this->lobjlandscapeform->CopyActive;?></td>
				</tr>

				<tr>
					<td colspan="4"><?php echo $this->translate("Copy From");?></td>
				</tr>
<tr>
					<td><?php echo $this->translate("Intake");?></td>
					<td><?php echo $this->lobjlandscapeform->CopyFromIdStartSemester;?></td>
					<td><?php echo $this->translate("Scheme");?></td>
	    			<td><?php echo $this->lobjlandscapeform->CopyFromScheme;?></td>
				</tr>



	</table>
	</div>

<div id = "table44" class="table" style="float:right;" >
		<table class="table" width="100%">
			<tr  align = "right">
            	<input  align = "right" type="button" class="NormalBtn" onClick="copyfirstlandscape();" dojotype="dijit.form.Button" label="<?php echo $this->translate("Copy"); ?>"  />
             </tr>
		</table>
	</div>

<!-- SEMESTER LANDSCAPE COPY  ENDS  -->



	</Form>
</fieldset>
<script language="JavaScript" type="text/javascript">
function copyfirstlandscape() {
$('#targetCopy').show();
var copyfrom_intakes = dijit.byId('CopyFromIdStartSemester').value;
var copyfrom_schemes = dijit.byId('CopyFromScheme').value;
var id_program = '<?php echo $this->IdProgram;?>';
var copy_schemes = dijit.byId('CopyScheme').value;
var copy_intake = dijit.byId('CopyIdStartSemester').value;
var copy_active = dijit.byId('CopyActive').value;

$.post("<?php echo $this->baseUrl();?>/generalsetup/landscape/copyfirstlandscape", { copyfrom_intakes: copyfrom_intakes, copyfrom_schemes: copyfrom_schemes, id_program: id_program, copy_intake: copy_intake, copy_active: copy_active, copy_schemes: copy_schemes},
   function(data) {
     if(data=='done') {
     	window.location.href= "<?php echo $this->baseUrl();?>/generalsetup/landscape/addlandscape/id/<?php echo $this->IdProgram;?>";
       } else {  
           $('#targetCopy').text('No Matching Landscape Found');
           $('#targetCopy').show(); 
       }
   });


}
</script>

