<fieldset>
<legend>Semester Academic Landscape</legend>
<table width="100%" class="table">
<tr>
	<td>Scheme :</td>
	<td><?php echo $this->larrdetails['Scheme'] ?></td>
</tr>
<tr>
	<td>Faculty :</td>
	<td><?php echo $this->faculty_name; ?></td>
</tr>
<tr>
	<td>Program :</td>
	<td><?php echo $this->larrdetails['ProgramName'] ?></td>
</tr>
<tr>
	<td>Intake :</td>
	<td><?php echo $this->intake_name; ?></td>
</tr>
</table>
<table width="100%" class="table">
	<tr>
		<th>Semester</th>
		<th>Course Type</th>
		<th>Course ID</th>
		<th>Course Descripttion</th>
		<th>Credit Hours</th>
		<th>&nbsp;</th>
	</tr>
<?php foreach($this->larrsemesterlist as $key => $block) { ?>
	<tr>
		<td rowspan="<?php echo count($block); ?>"><?php echo $key; ?></td>
	<?php foreach($block as $item) { ?>
			<td><?php echo $item['SubjectType'] ?></td>
		<td><?php echo $item['SubCode'] ?></td>
		<td><?php echo $item['SubjectName'] ?></td>
		<td><?php echo $item['CreditHours'] ?></td>
		<td><a href="<?php echo $this->url(array('module'=>'generalsetup','controller'=>'landscape', 'action'=>'prereqsetup','id'=>$item['IdLandscapeSub']),'default',true);?>">Pre-Requisite</a> </td>
	</tr>
	<?php } ?>
<?php } ?>
</table>
<table class="table" width="100%">
	<tr align="right">
		<td><input type="button" class="NormalBtn"
			dojotype="dijit.form.Button"
			label="<?php echo $this->translate("Back"); ?>"
			onclick="window.location.href='<?php echo $this->url(array('module'=>'generalsetup','controller'=>'landscape', 'action'=>'addlandscape','id'=>$this->IdProgram),'default',true);?>';" />
		</td>
	</tr>
</table>
</fieldset>