<head>

<script type="text/javascript">

dojo.addOnLoad(function(){

	dijit.byId('IdCollege').set('value','');
	dijit.byId('IdCollege').set('placeHolder','Select');
	
	dijit.byId('IdStaff').set('value','');
	dijit.byId('IdStaff').set('placeHolder','Select');
	
	var form = dijit.byId("myForm");
	var value=form.attr('value').DepartmentType;
	//fnToggleCollegeDetails(value)	
	});

function validateDepartmentname( value, constraint )
{
	
// I believe the whole reason you have to hack at control to get it to 
// display an error is due to the nature of the xhrGet call. Since the
// call is being made asychronously, the method would have already
// returned a result to the html control before query has finished.
// Therefore you have to do the extra method calls below. Also note
// that when the form goes for submission, it calls each controls validator
// method again! Meaning it will query the webpage again.
var loginID = dijit.byId( "DepartmentName" );

var bNoNameFound =  ( "Error" == loginID.get( "state" ) ) ? false:true;

if( "" == loginID.value ) {
    // for some required=true is not kicking in, so we are forcing it.
    bNoNameFound = false;
}
else {      
    if( false == loginID._focused ) {
        console.log( "Checking username..." );
        dojo.xhrGet({
            url: "<?php echo $this->baseUrl();?>"+"/generalsetup/departmentmaster/getdepartmentname/DeptName/"+value,
            handleAs: 'text',
            content: { l: value},
            timeout: 10000, 
            load: function( data ) {
                if ( data ) {
                    // setting the state to error since the username is already taken
                    console.log(loginID)
                    bNoNameFound = false;
                    loginID.set( "state", "Error" );
                    loginID.displayMessage( "The Department is already taken..." );
                    // used to change the style of the control to represent a error
                    loginID._setStateClass();
                    console.log( "Invalid username" ); 
                }
                else
                {
                    bNoNameFound = true;
                    loginID.set( "state", "" );
                    loginID.displayMessage( "" );
                }
            }
        });
    }
}

return bNoNameFound;
}


function validateDepartmentCode( value, constraint )
{
	
// I believe the whole reason you have to hack at control to get it to 
// display an error is due to the nature of the xhrGet call. Since the
// call is being made asychronously, the method would have already
// returned a result to the html control before query has finished.
// Therefore you have to do the extra method calls below. Also note
// that when the form goes for submission, it calls each controls validator
// method again! Meaning it will query the webpage again.
	
var loginID = dijit.byId( "DeptCode" );

var bNoNameFound =  ( "Error" == loginID.get( "state" ) ) ? false:true;

if( "" == loginID.value ) {
    bNoNameFound = false;
}
else {      
    if( false == loginID._focused ) {
        dojo.xhrGet({
            url: "<?php echo $this->baseUrl();?>"+"/generalsetup/departmentmaster/getdepartmentcode/DeptCode/"+value,
            handleAs: 'text',
            content: { l: value},
            timeout: 10000, 
            load: function( data ) {              
                if ( data ) {
                    bNoNameFound = false;
                    loginID.set( "state", "Error" );
                    loginID.displayMessage( "The Department Code is already taken..." );
                    loginID._setStateClass();
                    console.log( "Invalid username" ); 
                }
                else
                {
                    bNoNameFound = true;
                    loginID.set( "state", "" );
                    loginID.displayMessage( "" );
                }
            }
        });
    }
}

return bNoNameFound;
}

	
function fnToggleCollegeDetails(value){
	if(value != "")
	{ 
		var xhrArgs = {
				url: "<?php echo $this->baseUrl();?>"+"/generalsetup/departmentmaster/getcolgbranchlist/value/"+value,
				handleAs:'json',
				load:function(data){ 
					AutoFillNextEditableDropDown("IdCollege",data); 
				}
		   }
		dojo.xhrGet(xhrArgs); 
	} 
}
function fnGetStaffList(IdStaff){ 
	if(IdStaff != "")
		{ 
			var xhrArgs = {
					url: "<?php echo $this->baseUrl();?>"+"/generalsetup/user/getstafflist/idStaff/"+IdStaff,
					handleAs:'json',
					load:function(data){ 
						dijit.byId('FromDate').set('value',data['JoiningDate']);
					}
			   }
			dojo.xhrGet(xhrArgs); 
		} 
	} 	 
function AutoFillNextEditableDropDown(EditableDropDownId,JSONText){
	dijit.byId(EditableDropDownId).setValue("");
	var ddwidget = dijit.byId(EditableDropDownId);
	ddwidget.setAttribute('disabled', false);
    var options = {
					label:"name",
					identifier:"key",
					items:JSONText
				  };
    ddwidget.store = new dojo.data.ItemFileReadStore( { data: options } );
}

</script> 
</head>
 <fieldset>
    <legend><?php echo $this->translate("$this->Department");?></legend>
                <Form dojoType="dijit.form.Form"  id="myForm" action="<?php echo $this->baseUrl();?>/generalsetup/departmentmaster/newdepartmentmaster" method="post"  name= "myForm">
                <script type="dojo/method" event="onSubmit">
                if (this.validate()) {
					return true;
                } else {
                    return false;
                }
				</script>
                    <table class="table" width="100%" >
                        <tr>
                            <th colspan = "4"><?php echo $this->translate("$this->Department").' '.$this->translate("Details");?></th>
                        </tr>
                        <tr>
                            <td><?php echo $this->translate("$this->Department").' '.$this->translate("Name");?><span class="reqMark">*</span></td>
                            <td><?php echo $this->lobjdepartmentmasterForm->DepartmentName;?>
                            <td><?php echo $this->translate($this->defaultlanguage);?></td>
                            <td><?php echo $this->lobjdepartmentmasterForm->ArabicName;?></td>

                          </tr>  
                   
                            <?php echo $this->lobjdepartmentmasterForm->UpdDate;?>
                            <?php echo $this->lobjdepartmentmasterForm->UpdUser;?>
                       <tr> 
                            <td><?php echo $this->translate("Short Name");?><span class="reqMark">*</span></td>
                            <td><?php echo $this->lobjdepartmentmasterForm->ShortName;?></td>
                      		<td ><?php echo $this->translate("$this->Department").' '.$this->translate("Code");?><span class="reqMark">*</span></td>
                            <td  ><?php echo $this->lobjdepartmentmasterForm->DeptCode;?></td>
  
                        </tr>
                        <tr> 
                        	<!--<td ><?php echo $this->translate("$this->Department").' '.$this->translate("Type");?><span class="reqMark"></span></td>
                      		<td><?php echo $this->lobjdepartmentmasterForm->DepartmentType;?></td>
                            --><td ><span id="label1"><?php echo $this->translate("$this->College");?></span><span class="reqMark">*</span></td>
                            <td ><?php echo $this->lobjdepartmentmasterForm->IdCollege;?></td>
                        </tr>                 
                         <tr>
                          <th colspan = "4"><?php echo $this->translate('Head').' '.$this->translate("of").' '.$this->translate($this->Department).$this->translate("Details");?></th>
                        </tr>
                         <tr>
                            <td><?php echo $this->translate('Head').' '.$this->translate("of").' '.$this->translate($this->Department);?><span class="reqMark">*</span></td>
                            <td><?php echo $this->lobjdepartmentmasterForm->IdStaff;?></td>
                        	<td><?php echo $this->translate("Joining").' '.$this->translate("Date");?><span class="reqMark">*</span></td>
                        	<td><?php echo $this->lobjdepartmentmasterForm->FromDate;?><?php echo $this->lobjdepartmentmasterForm->ToDate;?></td>
                        </tr>
                        <tr>
                           <td><?php echo $this->translate("Active");?><span class="reqMark"></span></td>
                        	<td ><?php echo $this->lobjdepartmentmasterForm->Active;?></td>
                        	<td></td>
                        	<td></td>
                        </tr>
                        <tr>
                            <td align = "right" colspan="4"><?php echo $this->lobjdepartmentmasterForm->Save;?>
                            <input type='button' class="NormalBtn" dojotype="dijit.form.Button" label = "<?php echo $this->translate('Back')?>" value='click' onclick="window.location.href='<?php echo $this->url(array('module'=>'generalsetup','controller'=>'departmentmaster', 'action'=>'index'),'default',true);?>';" />	
                            </td> 
                        </tr>
              </table>
            
            </Form>

</fieldset>
