fieldset>
	<legend><?php echo $this->translate("Manajemen Audit")?></legend>
		<form method="post" id="form" name="form">
			<input type="hidden" name="id" id="id" value="">
			<table width="100%">
				<tr>
					<td align="right">Auditi :</td>
					<td>
						<select name="unit" style="resize:none;width:274px;height:25px">
							<option label="Text Here">
						</select>
					</td>
				</tr>
				<tr>
					<td align="right">ext :</td>
					<td><input type="date" name="mulai_audit" required></td>
				</tr>
				<tr>
					<td align="right">Tanggal Notifikasi :</td>
					<td><input type="date" name="notif" required></td>
				</tr>
				<tr>
					<td align="right">Tanggal Kirim Checklist :</td>
					<td><input type="date" name="kirim_cheklist" required></td>
					<td align="right">Tanggal Validasi Temuan Audit : </td>
					<td><input type="date" name="val_temuan_audit" required></td>
				</tr>
				<tr>
					<td align="right">Tanggal Kumpul Checklist :</td>
					<td><input type="date" name="kumpul_cheklist" required></td>
					<td align="right">Tanggal Validasi Rekomendasi TPP :</td>
					<td><input type="date" name="val_rekomendasi" required></td>
				</tr>
				<tr>
					<td align="right">Tanggal Visitasi :</td>
					<td><input type="date" name="visitasi" required></td>
					<td align="right">Tanggal Validasi Verifikasi TPP :</td>
					<td><input type="date" name="val_verivikasi" required></td>
				</tr>
				<tr>
					<td colspan="4" align="center">
					<input type="submit" name="Save" value="Save"></td>
				</tr>
					<table width="100%" class="table">
						<tr>
							<th width="20%">Tanggal Mulai Audit</th>
							<th width="40%">Audit</th>
							<th width="20%"></th>
							<th width="20%">Action</th>
						</tr>
					</table>
			</table>
		</form>
</fieldset>