<fieldset>
	<table>
		<tr>
			<td><a href="<?php echo $this->baseUrl();?>/perencanaanaudit/penjadwalan-audit/"><button type="button">Penjadwalan Audit</button></a>
			<a href="#"><button type="button">Tim Pelaksanaan Audit</button></td></a>
		</tr>
        	
        		<form action="">
        			<table width="100%">
        			<legend><?php echo $this->translate("Tim Pelaksana Auditor")?></legend>
        				<tr>
        					<td>Auditor :</td>
        					<td>
        						<select>
        							<option>Text Goes Here</option>
        						</select>
        					</td>
        				</tr>
        				<tr>
        					<td colspan="2" align="center">
        					<input type="submit" name="Save" value="Save"></td>
        				</tr>
        					<table width="100%" class="table">
        						<tr>
        							<th>Auditor</th>
        							<th>Action</th>
        						</tr>
        					</table>
        			</table>
        		</form>
		</table>
</fieldset>