<?php foreach ($this->result as $data) {?>
<fieldset>
<legend><?php echo $this->translate("Referensi Kriteria Audit")?></legend>
    <form  method="post" id="form" name="form">
    	<input type="hidden" name="id" id="id" value="<?php echo $data['kd_ref_kriteria_audit']; ?>">
        <table width="100%">
        	<tr>
        		<td>Nomor Standar Audit :</td>
        		<td><input type="text" name="nomor" value="<?php echo $data['no_standar_audit'];?>" required></td>
        	</tr>
        	<tr>
        		<td>Keterangan Standar Audit : </td>
        		<td><textarea name="ket"><?php echo $data['ket_standar_audit']; ?></textarea></td>
        	</tr>
        	<tr>
        		<td colspan="2" align="center">
        		<input type="submit" name="Save" value="Save"></td>
        	</tr>
        </table>
    </form>
</fieldset>
<?php } ?>