<script type="text/javascript">
  function validateForm(){
    var emaillogin = $('#Emaillogin').val();    
    var flag = false;
    var msg = '';
    var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

    if(emaillogin == ''){
      flag = true;
      msg = msg + 'Please enter Email';
    }else{
      if(reg.test(emaillogin) == false) {
        flag = true;
        msg = msg + "\n" +'Invalid Email Address';
      }
    }
    
    if(flag){
      alert(msg);
      return false;
    }
    return true;
  }
</script>
<body>
  <form onsubmit="return validateForm()" enctype="multipart/form-data" dojoType="dijit.form.Form" id="registrationApplicant" action="" method="POST"  name= "mylobjStudentApplicationForm">
    <div id="contentArea">
      <div class="section" id="content1">
        <?php
            if(isset($this->msg) && $this->msg!=""){
        ?>
          <ul class="apponlineerrors">
            <li><?php echo $this->msg; ?></li>
          </ul>
        <?php } ?>
        <table width=width="100%" border="0" cellspacing="10" cellpadding="10">
          <tr>
            <td><?php echo $this->translate("Email");?> <span class="reqMark">*</span>&nbsp;&nbsp;</td>
            <td><?php echo $this->forgotpasswordForm->Emaillogin;?></td>
          </tr>
        </table>
          <input type="submit" id="submit" value="Submit">
      </div>
    </div>
</form>
</body>

