<select id="program_<?php echo $this->intake;?>" class="" style="width:200px;" name="program_<?php echo $this->intake?>">
  <?php if(count($this->program) > 1 || count($this->program) == 0){?>
  <option value=''>select</option>
  <?php }?>
<?php foreach($this->program as $program){?>
  <option value='<?php echo $program['key'];?>'><?php echo $program['value']; ?></option>
  <?php } ?>
</select>
<?php exit; ?>