<table>
</br>
</table>
<table border="0" padding-left = "20px" cellspacing="0" cellpadding="0" width="100%" align = "center">
<tr><td width="25%"></td>
<td width="50%">
<table border="0" padding-left = "20px" cellspacing="0" cellpadding="0" width="100%" align = "center">
  <!--<tr>
    <td>Our Ref </td>
    <td width="89%" colspan="2">:</td>
  </tr>-->

  <tr>
  	<?php $ldtsystemDate = date ( 'd-m-Y' );?>
    <td colspan=3 align="right">Date :<?php echo $ldtsystemDate;?></td>
  </tr>
  <tr>
    <td width="100%" colspan="3">&nbsp;</td>
  </tr>
  <tr>
    <td width="100%" colspan="3"> &nbsp;</td>

  </tr>
  <tr>
    <td width="100%" colspan="3">Dear <?php echo $this->FName.' '.$this->MName.' '.$this->LName;?>, </td>
  </tr>
  <tr>
    <td width="100%" colspan="3">&nbsp;</td>
  </tr>
  <tr>

    <td width="100%" colspan="3"><strong><u>RE: CONDITIONAL OFFER LETTER</u></strong> </td>
  </tr>
  <tr>
    <td width="100%" colspan="3">&nbsp; </td>
  </tr>
  <tr>
    <td width="100%" colspan="3">We are pleased to inform you that  your application to the programme of studies at <?php echo $this->ShortName;?> is successful. Details of the programme are as follows:</td>

  </tr>
  <tr>
    <td width="100%" colspan="3">&nbsp;</td>
  </tr>
    <tr>
    <td colspan="2">PROGRAMME  </td>
    <td width="78%">:<?php echo $this->ProgramName;?></td>
  </tr>   
  <!-- <tr>
    <td width="100%" colspan="3"> &nbsp;</td>
  </tr>-->

  
  <!--<tr>
    <td width="100%" colspan="3"> &nbsp;</td>
  </tr>
  <tr>
    <td colspan="2">Date</td>
    <td width="78%">:</td>
  </tr>-->
  <!--<tr>
    <td>Venue</td>
    <td  colspan="2"width="78%" valign="top">: <?php echo $this->CollegeName;?></td>
  </tr>
  --><!--<tr>
    <td colspan="2">Time</td>
    <td width="78%">: </td>
  </tr>
  <tr>
    <td colspan="2">Commencement of Semester</td>
    <td width="78%" valign="top">: </td>
  </tr>-->
  <tr>

    <td width="100%" colspan="3">&nbsp; </td>
  </tr>
  <tr>
    <td width="100%" colspan="3">We will contact you in 10 working days.<br>
          
      <br>
      Should you have any queries, please feel free to contact us at    <?php echo $this->Email;?><br>
      Congratulations and we look    forward to welcoming you to Allianze University College of Medical Sciences

      <br>
      Thank you.</td>
  </tr>
  <tr>
    <td width="100%" colspan="3">&nbsp;</td>
  </tr>
 
  <tr>
    <td width="100%" colspan="3">&nbsp;</td>

  </tr>
  <tr>
    <td width="100%" colspan="3">For Registrar<br>
    Allianze University College of Medical Sciences
      <?php echo $this->CollegeName;?></td>
  </tr>
</table><br><br><br><br>
<strong>---------------------------------------------------------------------------------</strong><br>
  
</td><td width="25%"></td></tr>
</table>	