<fieldset>
 <legend><?php echo $this->translate("Scheme Setup Search ");?></legend>
          <form action="<?php echo $this->baseUrl();?>/generalsetup/schemesetup/index/search/1" method="POST">
           <table width="100%">
              <tr>
                  <td ><?php echo $this->translate("English Description");?></td>
                  <td ><?php echo $this->lobjform->field2;?></td>
                  <td ><?php echo $this->translate($this->defaultlanguage);?></td>
                  <td ><?php echo $this->lobjform->field3;?></td>
              </tr>
               <tr>
                  <td ><?php echo $this->translate("Scheme Code");?></td>
                  <td ><?php echo $this->lobjform->field4;?></td>
                  <td ><?php echo $this->translate("Active");?></td>
                  <td ><?php echo $this->lobjform->field7;?></td>
                  
               </tr>
                <tr>
                   <td align = "center" colspan = "4">
                   <?php echo $this->lobjform->Search;?>
				   <input type='button' class="NormalBtn" dojotype="dijit.form.Button" label = "<?php echo $this->translate('Add')?>" value='Add' onclick="window.location.href='<?php echo $this->url(array('module'=>'generalsetup','controller'=>'schemesetup', 'action'=>'newschemesetup'),'default',true);?>';" />
				   <?php echo $this->lobjform->Clear;?></td>
				</tr>
            </table>
         </form>	
</fieldset> 
    <br/>


<fieldset>
	<table class="table" width="100%" cellpadding="5" cellspacing="1">
	    	<tr>
	        	<th><?php echo $this->translate("English Description");?></th>
	       	    <th><?php echo $this->translate($this->defaultlanguage);?></th>
	       	    <th><?php echo $this->translate("Scheme Code");?></th>
	    	</tr>
	        <?php if (count($this->paginator)): ?>
	        <?php foreach ($this->paginator as $lobjscheme ): ?>
	  		<tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next()?>">
	        	<td><a href="<?php echo $this->url(array('module'=>'generalsetup','controller'=>'schemesetup', 'action'=>'schemesetuplist' , 'id'=>$lobjscheme['IdScheme']),'default',true);?>" ><?php print_r($this->escape($lobjscheme['EnglishDescription']));?></a></td>
                <td><?php echo $this->escape($lobjscheme['ArabicDescription']);?></td>
	        	<td><?php echo $this->escape($lobjscheme['SchemeCode']);?></td>
	        </tr> 
	        <?php endforeach; ?>
	            <?php endif; ?> 
			
			<tr>
	          <td colspan="3" align="right"><div class="pagination"><?php echo $this->paginationControl($this->lobjpaginator,'Sliding','/partials/my_pagination_control.phtml'); ?></div></td>
            </tr>
	</table>
</fieldset>