
<script type="text/javascript">
	$(function() {
		 $( "#tabs" ).tabs();
	});


function back(){
	window.location = "<?php echo $this->url(array('module'=>'generalsetup','controller'=>'landscape','action'=>'landscape-list','id'=>$this->programId),'default',true);?>";
}

function addCourse(type,idMajoring){	

	url = "<?php echo $this->url(array('module'=>'generalsetup','controller'=>'landscape', 'action'=>'add-course','idlandscape'=>$this->landscapeId,'id'=>$this->programId),'default',true); ?>/idMajoring/"+idMajoring+"/type/"+type;

	$("#dialog-add-course").slideDown("slow");
	$('#dialog-add-course').load(url);
	
	
}



function validateTotalCreditHours(){
	
	var IdProgramReq = $('select[name="IdProgramReq"]').val();
	
		
		//check dah exceed ke credit hours
		if(IdProgramReq!=''){
			
				$.ajax({
					url: "<?php echo $this->url(array('module'=>'generalsetup','controller'=>'landscape', 'action'=>'ajax-get-program-requirement','idlandscape'=>$this->landscapeId,'idprogram'=>$this->programId),'default',true);?>",
					data: {'IdProgramReq':IdProgramReq},
					type: 'POST',
					dataType: 'json'	
				}).done(function ( data ) {	
		
					if(data.status==0){
						alert("Sorry you have exceed total credit hours for this particular Subject Type");	
						$('#IdProgramReq').get(0).selectedIndex = 0;
					}else{
						$('#SubjectType').val(data.SubjectType);
					}
					
				});
		}//end if
	
}


function getCreditHours(e){

	//var SubjectType = $('select[name="SubjectType"]').val();
	var SubjectType = $('#SubjectType').val();

	if(SubjectType!=''){
			$.ajax({
				url: "<?php echo $this->url(array('module'=>'generalsetup','controller'=>'landscape', 'action'=>'ajax-get-subject','idlandscape'=>$this->landscapeId,'id'=>$this->programId),'default',true);?>",
				data: {'IdSubject':$(e).val(),'SubjectType':SubjectType},
				type: 'POST',
				dataType: 'json'	
			}).done(function ( data ) {
		
				if(data.status==0){
					alert("Sorry you cannot choose this Subject. The Course Credit Hour has exceeded available balance Minimum Requirement Credit Hours. Available balance credit hours is "+data.available);
					$('#IdSubject').get(0).selectedIndex = 0;						
				}else{
					$('#CreditHours').val(data.CreditHours);					
				}
			});
	}else{
		alert("Please Select Subject Type First.");
		$('#IdSubject').get(0).selectedIndex = 0;
	}
}
</script>

<div class="breadcrum">
	<ul class="tri-steps">
		<li class="empty"><div class="text"><a href="<?php echo $this->url(array('module'=>'generalsetup','controller'=>'landscape','action'=>'edit-landscape','idlandscape'=>$this->landscapeId,'id'=>$this->programId),'default',true);?>"><?php echo $this->translate("Info"); ?></a></div></li>
		<li class="prevDone"><div class="text"><a href="<?php echo $this->url(array('module'=>'generalsetup','controller'=>'landscape','action'=>'program-requirement','idlandscape'=>$this->landscapeId,'id'=>$this->programId),'default',true);?>"><?php echo $this->translate("Program Requirments"); ?></a></div></li>
		<li class="lastCurrent"><div class="text"><a href="<?php echo $this->url(array('module'=>'generalsetup','controller'=>'landscape','action'=>'course-landscape','idlandscape'=>$this->landscapeId,'id'=>$this->programId),'default',true);?>"><?php echo $this->translate("Course"); ?></a></div></li>	
	</ul>
	<div class="clear"></div>
</div>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>	
			
		  	<li>
				<a href="#" onclick="back()" >
					<span class='back'></span>
					Back
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>

<br>

	
<div id="dialog-add-course" title="Add Course" style="display:none">
<fieldset><legend><?php echo $this->translate("Add Course Form")?></legend>
<?php //echo $this->form; ?>
</fieldset>
<br><br>
</div>
		
<div style="width:100%;">
<fieldset><legend><?php echo $this->translate("Program Requirement List")?></legend>
<table class="table" width="70%" cellpadding="5" cellspacing="0" border="0">
		<tr>
			<th width="200">Course Type</th>
			<th width="100px">Compulsory</th>
			<th width="100px">Minimum Credit Hours</th>
			
		</tr>
		  
		  
		   <?php 
		   if(count($this->programrequirement)>0){
		   	 $total_credit_hours=0;
		  	 foreach($this->programrequirement as $req){
		  	 	
		  	 $total_credit_hours = $total_credit_hours + $req["CreditHours"];
		  	?>
			<tr class='shade'>
				<td><?php echo $req["DefinitionDesc"]?></td>
				<td align="center"><?php echo ($req["Compulsory"]==1) ? $this->translate("Yes"): $this->translate("No")?></td>
				<td align="center"><?php echo $req["CreditHours"]?></td>
			</tr>
			<?php } //end foreach ?>
		   
						
		<tr>
			<td align="right" colspan=2>Total : </td>
			<td align="center"><strong><?php echo $total_credit_hours;?></strong></td>			
		</tr>
		<?php }//end if ?>
	</table>
</fieldset>

<br><br><br><br>

<fieldset><legend><?php echo $this->translate("Common Courses")?></legend>

  <h1><?php echo $this->translate("Compulsory Courses")?></h1><br>
  <div class="span-7 buttons">
   	<a class="positive addLink" href="#" onClick="javscript:addCourse(1,0);">Add Compulsory Course  </a> 
  </div>
  <br>
   <table class="table" width="100%" cellpadding="5" cellspacing="2" border="0">
				<tr>					
					<th width="50px">Semester</th>
					<th width="200">Course Name</th>
					<th width="50px">Course Code</th>
					<th width="100px">Course Type</th>					
					<th width="50px">Credit Hour</th>
					<th width="50px">Action</th>
				</tr>
				
				<?php 
				if(is_array($this->compulsory_course)){
					$total_credit_hours=0;
					foreach($this->compulsory_course as $common) { 			
								
						$total_credit_hours = $total_credit_hours + $common["CreditHours"];
												
				?>
					<tr class='shade'>
						<td align="center"><?php echo $common["IdSemester"]?></td>
						<td align="left"><?php echo $common["BahasaIndonesia"]?></td>
						<td align="center"><?php echo $common["SubCode"]?></td>
						<td align="center"><?php echo $common["DefinitionDesc"]?></td>						
						<td align="center"><?php echo $common["CreditHours"]?></td>
						<td align="center">
						<a href="<?php echo $this->url(array('module'=>'generalsetup','controller'=>'landscape', 'action'=>'delete-course','idlandscape'=>$this->landscapeId,'id'=>$this->programId,'idLandscapeSub'=>$common["IdLandscapeSub"]),'default',true)?>"><img src='<?php echo $this->baseUrl();?>/images/delete.png'  border=0 width='16' height='16'></a>
						&nbsp;
						<a href="<?php echo $this->url(array('module'=>'generalsetup','controller'=>'landscape','action'=>'add-prerequisite','idlandscape'=>$this->landscapeId,'id'=>$this->programId,'idSubject'=>$common["IdSubject"],'idLandscapeSub'=>$common["IdLandscapeSub"]),'default',true);?>"><img src='<?php echo $this->baseUrl();?>/images/add.png' title="Manage Prerequisite" border=0 width='16' height='16'></a>
						</td>
					</tr>
				<?php } }?>
				<tr>
						<td align="right" colspan="4" bgcolor="#F5F6CE"><strong><?php echo $this->translate("Total")?></strong></td>
						<td align="center" bgcolor="#F5F6CE"><strong><?php echo $total_credit_hours;?></strong></td>						
				</tr>
		   </table>
		   
  <br>
  
  <h1><?php echo $this->translate("Not Compulsory Courses")?></h1><br>
  <div class="span-7 buttons">
   	<a class="positive addLink" href="#" onClick="javscript:addCourse(2,0);">Add Not Compulsory Course  </a> 
  </div>
   <table class="table" width="100%" cellpadding="5" cellspacing="2" border="0">
				<tr>					
					<th width="50px">Semester</th>
					<th width="200">Course Name</th>
					<th width="50px">Course Code</th>
					<th width="100px">Course Type</th>					
					<th width="50px">Credit Hour</th>
					<th width="50px">Action</th>
				</tr>
				
				<?php 
				if(is_array($this->elective_course)){
					$total_elective_credit_hours=0;
					foreach($this->elective_course as $elective) { 			
								
						$total_elective_credit_hours = $total_elective_credit_hours + $elective["CreditHours"];
												
				?>
					<tr class='shade'>
						<td align="center"><?php echo $elective["IdSemester"]?></td>
						<td align="left"><?php echo $elective["BahasaIndonesia"]?></td>
						<td align="center"><?php echo $elective["SubCode"]?></td>
						<td align="center"><?php echo $elective["DefinitionDesc"]?></td>						
						<td align="center"><?php echo $elective["CreditHours"]?></td>
						<td align="center"><a href="<?php echo $this->url(array('module'=>'generalsetup','controller'=>'landscape', 'action'=>'delete-course','idlandscape'=>$this->landscapeId,'id'=>$this->programId,'idLandscapeSub'=>$elective["IdLandscapeSub"]),'default',true)?>"><img src='<?php echo $this->baseUrl();?>/images/delete.png'  border=0 width='16' height='16'></a></td>
					</tr>
				<?php } }?>
				<tr>
						<td align="right" colspan="4" bgcolor="#F5F6CE"><strong><?php echo $this->translate("Total")?></strong></td>
						<td align="center" bgcolor="#F5F6CE"><strong><?php echo $total_elective_credit_hours;?></strong></td>						
				</tr>
		   </table>
  	      
</fieldset>	

<br><br><br><br>


<fieldset><legend><?php echo $this->translate("Majoring Courses")?></legend>

<div id="tabs">
	<ul>    	
	<?php 
		if($this->majoring){		
			$i=1;	
			foreach($this->majoring as $major){
	?>
    		<li><a href="#tabs-<?php echo $i?>"><?php echo $major["BahasaDescription"]?></a></li>  
    	  
    <?php	$i++; } //end foreach 
		} //end if
	?>   		
  	</ul>
  	
  	
  	<?php 
		if($this->majoring){		
			$i=1;	
			foreach($this->majoring as $major){
				
				$landscapeSubjectDb =  new GeneralSetup_Model_DbTable_Landscapesubject();
				$compulsory_majoring_course = $landscapeSubjectDb->getMajoringCourse($this->programId,$this->landscapeId,$major["IDProgramMajoring"],1);
				$notcompulsory_majoring_course = $landscapeSubjectDb->getMajoringCourse($this->programId,$this->landscapeId,$major["IDProgramMajoring"],2);
				
	?>
  	<div id="tabs-<?php echo $i?>">  	       
  	      
  	    <br>
		<h1><?php echo $this->translate("Compulsory Courses")?></h1><br>
		<div class="span-7 buttons">
   			 <a class="positive addLink" href="#" onClick="javscript:addCourse(1,'<?php echo $major["IDProgramMajoring"];?>');">
    			Add Compulsory Course       
    	</a>
		</div>
		
		<br>
		
  	       <table class="table" width="100%" cellpadding="5" cellspacing="2" border="0">
				<tr>					
					<th width="50px">Semester</th>
					<th width="200">Course Name</th>
					<th width="50px">Course Code</th>
					<th width="100px">Course Type</th>					
					<th width="50px">Credit Hour</th>
					<th width="50px">Action</th>
				</tr>
				
				<?php 
				if(is_array($compulsory_majoring_course)){
					$total_major_credit_hours=0;
					foreach($compulsory_majoring_course as $major) { 			
								
						$total_major_credit_hours = $total_major_credit_hours + $major["CreditHours"];
												
				?>
					<tr class='shade'>
						<td align="center"><?php echo $major["IdSemester"]?></td>
						<td align="left"><?php echo $major["BahasaIndonesia"]?></td>
						<td align="center"><?php echo $major["SubCode"]?></td>
						<td align="center"><?php echo $major["DefinitionDesc"]?></td>						
						<td align="center"><?php echo $major["CreditHours"]?></td>
						<td align="center"><a href="<?php echo $this->url(array('module'=>'generalsetup','controller'=>'landscape', 'action'=>'delete-course','idlandscape'=>$this->landscapeId,'id'=>$this->programId,'idLandscapeSub'=>$major["IdLandscapeSub"]),'default',true)?>"><img src='<?php echo $this->baseUrl();?>/images/delete.png'  border=0 width='16' height='16'></a></td>
					</tr>
				<?php } }?>
				<tr>
						<td align="right" colspan="4" bgcolor="#F5F6CE"><strong><?php echo $this->translate("Total")?></strong></td>
						<td align="center" bgcolor="#F5F6CE"><strong><?php echo $total_major_credit_hours;?></strong></td>						
				</tr>
				
		   </table>
		   
		   <br>
		   
		   <h1><?php echo $this->translate("Not Compulsory Courses")?></h1><br>
		   <div class="span-7 buttons">
   			 <a class="positive addLink" href="#" onClick="javscript:addCourse(2,'<?php echo $major["IDProgramMajoring"];?>');">
    			Add Not Compulsory Course       
    		</a>
			</div>
			
			 <table class="table" width="100%" cellpadding="5" cellspacing="2" border="0">
				<tr>					
					<th width="50px">Semester</th>
					<th width="200">Course Name</th>
					<th width="50px">Course Code</th>
					<th width="100px">Course Type</th>					
					<th width="50px">Credit Hour</th>
					<th width="50px">Action</th>
				</tr>
				
				<?php 
				if(is_array($notcompulsory_majoring_course)){
					$total_major_credit_hours=0;
					foreach($notcompulsory_majoring_course as $major) { 			
								
						$total_major_credit_hours = $total_major_credit_hours + $major["CreditHours"];
												
				?>
					<tr class='shade'>
						<td align="center"><?php echo $major["IdSemester"]?></td>
						<td align="left"><?php echo $major["BahasaIndonesia"]?></td>
						<td align="center"><?php echo $major["SubCode"]?></td>
						<td align="center"><?php echo $major["DefinitionDesc"]?></td>						
						<td align="center"><?php echo $major["CreditHours"]?></td>
						<td align="center"><a href="<?php echo $this->url(array('module'=>'generalsetup','controller'=>'landscape', 'action'=>'delete-course','idlandscape'=>$this->landscapeId,'id'=>$this->programId,'idLandscapeSub'=>$major["IdLandscapeSub"]),'default',true)?>"><img src='<?php echo $this->baseUrl();?>/images/delete.png'  border=0 width='16' height='16'></a></td>
					</tr>
				<?php } }?>
				<tr>
						<td align="right" colspan="4" bgcolor="#F5F6CE"><strong><?php echo $this->translate("Total")?></strong></td>
						<td align="center" bgcolor="#F5F6CE"><strong><?php echo $total_major_credit_hours;?></strong></td>						
				</tr>
				
		   </table>
		
		<br>
		
  	</div>
  	<?php	$i++; } //end foreach 
		} //end if
	?>   
	
</div>
</fieldset>


<br>
<br>
<br>
<br>
