<script type="text/javascript">
<!--
var ProgramCreditHours = <?php echo $this->programcredit ?>;
var PRCreditH = 0;
var TotalSubHours = 0;
var PRCreditH = 0;
var LSubCreditH = new Array();
var PRSubCreditH = new Array();
var BalanceHours = new Array();
var AddHours = new Array();
var trs = 0;
var courseTypeArray = new Array();

var courseDataAndTypeArray = new Array();

var rowid = 1;
var rowid1 = 1;
var rowid2 = 1;
var rowid3 = 1;
var rowid4 = 1;
var rowid5 = 1;
	dojo.addOnLoad(function() {
		dijit.byId('IdStartSemester').set('value','');
		dijit.byId('IdStartSemester').set('placeHolder','Select');
                dijit.byId('Scheme').set('value','');
                dijit.byId('Scheme').set('placeHolder','Select');
                dijit.byId('CopyScheme').set('value','');
                dijit.byId('CopyScheme').set('placeHolder','Select');
                dijit.byId('CopyFromScheme').set('value','');
                dijit.byId('CopyFromScheme').set('placeHolder','Select');
	});

	//SHOWING PROGRAMREQUIREMENT
	function showprogreq() {
		var flag = true;
		var IdStartSemester = dijit.byId("IdStartSemester");
		if(IdStartSemester.get('value')== "") {
			IdStartSemester.set('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}
		if(flag == true) {
			dojo.byId("prgreq").style.display = "block";
			ProgramCreditHours = dijit.byId("TotalCreditHours").value;
			dojo.attr("TotalCreditHours", "readonly", true);
		}
		return flag;
	}

	function addLandscapeDetails() {
		var flag = true;
		if(dijit.byId("SubjectType")==''){
		    dijit.byId("SubjectType").attr('required','true');
			dijit.byId("SubjectType").focus();flag = false;
		}

		var SubjectType = dijit.byId("SubjectType");
		if(SubjectType.get('value')== "")
		{
			SubjectType.set('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}

		if(!dijit.byId("CreditHours").isValid()){
			dijit.byId("CreditHours").focus();
			flag = false;
		}

		if(dijit.byId("CreditHours").value==''){
		    dijit.byId("CreditHours").attr('required','true');
			dijit.byId("CreditHours").focus();flag = false;
		}

		if(flag == true) {
			podetailsInsert();
		}
		return flag;
	}

	var batchArray  = new Array();
	var addsubArray  = new Array();
        var uniquesubArray  = new Array();
	var subjArray = new Array();

	function podetailsInsert() {
		var SubjectType = dijit.byId("SubjectType");
		var SubjectTypename = dijit.byId("SubjectType").displayedValue;
		var CreditHours = dijit.byId("CreditHours").value;
		PRCreditH = parseFloat(PRCreditH) + parseFloat(CreditHours);

		PRSubCreditH[SubjectType] = CreditHours;
		LSubCreditH[SubjectType] = 0;
		BalanceHours[SubjectType] = CreditHours;
		AddHours[SubjectType] = 0;



		if(parseFloat(PRCreditH) <= parseFloat(ProgramCreditHours)) {
			batchArray.push(SubjectTypename);
			if(arrHasDupes(batchArray)) {
				batchArray = batchArray.unique();
				PRCreditH = parseFloat(PRCreditH) - parseFloat(CreditHours);
				alert("Duplicate Course Type");
			} else {
				var Balance = ProgramCreditHours - PRCreditH;
				dijit.byId("Balance").set('value',Balance);
				var trow=document.getElementById('horprg').insertRow(rowid);
				var tcol1=trow.insertCell(0);
				var tcol2=trow.insertCell(1);
				var tcol3=trow.insertCell(2);
				var tcol4=trow.insertCell(3);
				var tcol5=trow.insertCell(4);



				tcol1.innerHTML="<input type='hidden' value='"+SubjectType+"' name=SubjectTypegrid[]>"+SubjectTypename;
				tcol2.innerHTML="<input type='hidden' id = 'credit' value='"+CreditHours+"' name=CreditHoursgrid[]>"+CreditHours;
				tcol3.innerHTML="<input type='text' disabled='disabled' readonly = 'true' size = '2' style='background-color:#E5E5E5;'  id = 'id"+SubjectType+"' value='"+BalanceHours[SubjectType]+"' name=BalanceHoursgrid[]>";
				tcol4.innerHTML="<input type='text' disabled='disabled' readonly = 'true' size = '2' style='background-color:#E5E5E5;' id = 'ad"+SubjectType+"' value='0' name=AddHoursgrid[]>"
				tcol5.innerHTML="<a href='#' onClick='deleteRowprogram(this,"+CreditHours+","+Balance+","+SubjectType+"); return false;'><img src='<?php echo $this->baseUrl();?>/images/delete.png'  border=0 width='16' height='16'></a>";
				rowid++;
				courseTypeArray.push({key:SubjectType.value,name:SubjectTypename});
			}
		} else {

			PRCreditH = parseFloat(PRCreditH) - parseFloat(CreditHours);
			alert("Course Type Credit Hours Exceeds Program Credit Hours ");
		}
	}

	function deleteRowprogram(r,CrHr,Blc,SubjectType) {                                
                
                var dStat = confirm("Are you sure to delete?");
                var adHrs = 'ad'+SubjectType;
                var adHrsValue = document.getElementById(adHrs).value;
                //console.log(adHrsValue);
                if(adHrsValue=='0'){ 
                    if(dStat == true && adHrsValue=='0') {  
                                rowid--;
                                var i=r.parentNode.parentNode.rowIndex;
                                batchArray.splice(parseInt(i-1),1);
                                document.getElementById('horprg').deleteRow(i);
                                PRCreditH = parseFloat(PRCreditH) - parseFloat(CrHr);
                                var Balance = Blc + CrHr;
                                dijit.byId("Balance").set('value',Balance);
                        } else { }                        
                } else { 
                    alert("Can't Delete Course Type as it has Courses Associated with it.");    
                }                
                
	}

	function showtablesub() {
		AutoFillNextEditableDropDown("LandscapeSubjectType",courseTypeArray);
		if(PRCreditH < ProgramCreditHours) {
			alert("Course Type Total Credit Hours Should be Equal to Program Total Credit Hours");
			} else {

		var SemsterCount = dijit.byId('SemsterCount').value;
		dojo.byId("table2").style.display = "block";
		fnGetBlocksubList(SemsterCount);
		dojo.byId("tr2").style.display = "none";
		dijit.byId('IdSubject').set('value','');
		dijit.byId('IdSubject').set('placeHolder','Select');
		dijit.byId('LandscapeSubjectType').set('value','');
		dijit.byId('LandscapeSubjectType').set('placeHolder','Select');
			}
	}

	function fnGetBlocksubList(Blockcount){
		if(Blockcount != "") {
			var xhrArgs = {
				url: "<?php echo $this->baseUrl();?>"+"/generalsetup/landscape/getblocklist/Blockcount/"+Blockcount,
				handleAs:'json',
				load:function(data){
					AutoFillNextEditableDropDown("IdSemester",data);
				}
			}
			dojo.xhrGet(xhrArgs);
		}
	}

	function fngetcoursetype(){
		Blockcount = "1";
		if(Blockcount != "") {
			var xhrArgs = {
				url: "<?php echo $this->baseUrl();?>"+"/generalsetup/landscape/getcoursetype/",
				handleAs:'json',
				load:function(data){
					//console.log(data);
					AutoFillNextEditableDropDown("CourseType",data);
				}
			}
			dojo.xhrGet(xhrArgs);
			}
	}

	function fnGetLevelList(Blockcount){
		if(Blockcount != "") {
			var xhrArgs = {
				url: "<?php echo $this->baseUrl();?>"+"/generalsetup/landscape/getblocklist/Blockcount/"+Blockcount,
				handleAs:'json',
				load:function(data){
					AutoFillNextEditableDropDown("block",data);
				}
			}
			dojo.xhrGet(xhrArgs);
		}
	}

	function AutoFillNextEditableDropDown(EditableDropDownId,JSONText){
		dijit.byId(EditableDropDownId).setValue("");
		var ddwidget = dijit.byId(EditableDropDownId);
		ddwidget.setAttribute('disabled', false);
    	var options = {
			label:"name",
			identifier:"key",
			items:JSONText
		};
    	ddwidget.store = new dojo.data.ItemFileReadStore( { data: options } );
	}

	function fngetsubjectcredithours(idsubject) {
	if(idsubject != "") {
		var xhrArgs = {
			url: "<?php echo $this->baseUrl();?>"+"/generalsetup/landscape/fngetsubjectcredithours/idsubject/"+idsubject,
			handleAs:'text',
			load:function(data){
			dojo.byId('subcredithours').value = parseFloat(data);
			dojo.byId('chours').innerHTML = data;
		}
	}
	dojo.xhrPost(xhrArgs);
		}
	}

	function fnGetBlocksemList(Blockcount){
		if(Blockcount != "") {
			var xhrArgs = {
				url: "<?php echo $this->baseUrl();?>"+"/generalsetup/landscape/getblocklist/Blockcount/"+Blockcount,
				handleAs:'json',
				load:function(data){
					AutoFillNextEditableDropDown("BlockDtlsList",data);
				}
			}
			dojo.xhrGet(xhrArgs);
		}
	}

	function fnGetSemesterList(SemsterCount){
		if(SemsterCount != "")
			{
				var xhrArgs = {
						url: "<?php echo $this->baseUrl();?>"+"/generalsetup/landscape/semlist/SemsterCount/"+SemsterCount,
						handleAs:'json',
						load:function(data){
							AutoFillNextEditableDropDown("SemNameList",data);
						}
				   }
				dojo.xhrGet(xhrArgs);
			}
		}

	function fnGetBlocksub(Blockcount){
		if(Blockcount != "") {
			var xhrArgs = {
				url: "<?php echo $this->baseUrl();?>"+"/generalsetup/landscape/getblocklist/Blockcount/"+Blockcount,
				handleAs:'json',
				load:function(data){
                                    //console.log(data);
					AutoFillNextEditableDropDown("blocksub",data);
                                          //console.log(uniquesubArray);
                                          AutoFillNextEditableDropDown("subjectblock",uniquesubArray);
				}
			}
			dojo.xhrGet(xhrArgs);
		}
	}

	function addLandscapeprogDetails() {
		var flag = true;
		if(dijit.byId("IdSubject")==''){
		    dijit.byId("IdSubject").attr('required','true');
			dijit.byId("IdSubject").focus();flag = false;
		}
		var IdSubject = dijit.byId("IdSubject");
		if(IdSubject.get('value')== "") {
			IdSubject.set('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}

		if(dijit.byId("IdSemester")==''){
		    dijit.byId("IdSemester").attr('required','true');
			dijit.byId("IdSemester").focus();flag = false;
		}
		var IdSemester = dijit.byId("IdSemester");
		if(IdSemester.get('value')== ""){
			IdSemester.set('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}

		if(dijit.byId("LandscapeSubjectType")==''){
		    dijit.byId("LandscapeSubjectType").attr('required','true');
			dijit.byId("LandscapeSubjectType").focus();flag = false;
		}

		var LandscapeSubjectType = dijit.byId("LandscapeSubjectType");
		if(LandscapeSubjectType.get('value')== "") {
			LandscapeSubjectType.set('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}

		if(flag == true) {
			LandscapeprogInsert();
		}
		return flag;
	}
	function LandscapeprogInsert() {
		var IdSemester = dijit.byId("IdSemester");
		var IdSemestername = dijit.byId("IdSemester").displayedValue;

		var IdSubject = dijit.byId("IdSubject");
		var IdSubjectname = dijit.byId("IdSubject").displayedValue;

		var LandscapeSubjectType = dijit.byId("LandscapeSubjectType");
		var LandscapeSubjectTypename = dijit.byId("LandscapeSubjectType").displayedValue;

		var IdProgramMajoring = dijit.byId("IdProgramMajoring");
		var IdProgramMajoringname = dijit.byId("IdProgramMajoring").displayedValue;

		var SubjectCreditHours = 0;
		SubjectCreditHours = dojo.byId("subcredithours").value;

		//TotalSubHours = parseFloat(TotalSubHours) + parseFloat(SubjectCreditHours);
		var count = 0;
		LSubCreditH[LandscapeSubjectType] = parseFloat(LSubCreditH[LandscapeSubjectType]) + parseFloat(SubjectCreditHours);

		//console.log(LSubCreditH[LandscapeSubjectType]);

		if(parseFloat(LSubCreditH[LandscapeSubjectType])  <= parseFloat(PRSubCreditH[LandscapeSubjectType]))
		{

				//addsubArray.push(IdSubjectname);
                                courseDataAndTypeArray.push(IdSubjectname+'#'+LandscapeSubjectTypename);                                
                               
                                 uniquesubArray.push({key:IdSubject.value,name:IdSubjectname});
                                 uniquesubArray = uniquesubArray.unique();
				if(arrHasDupes(courseDataAndTypeArray))
				{
					courseDataAndTypeArray = courseDataAndTypeArray.unique();
					dojo.byId('subcredithours').value = '';
					//dijit.byId('IdSemester').set('value','');
					//dijit.byId('IdSemester').set('placeHolder','Select');
					dijit.byId('IdSubject').set('value','');
					dijit.byId('IdSubject').set('placeHolder','Select');
					document.getElementById('chours').innerHTML = '';
                                        LSubCreditH[LandscapeSubjectType] = LSubCreditH[LandscapeSubjectType]- parseFloat(SubjectCreditHours);
					alert("Duplicate Course and Course Type");
				} else {
					//LSubCreditH[LandscapeSubjectType] =  parseFloat(SubjectCreditHours);
					//BalanceHourse = BalanceHours[LandscapeSubjectType] - LSubCreditH[LandscapeSubjectType];
					BalanceHourse = BalanceHours[LandscapeSubjectType] - parseFloat(SubjectCreditHours);
                                        BalanceHours[LandscapeSubjectType] = BalanceHourse;
					var idS = 'id'+LandscapeSubjectType;
					dojo.byId(idS).value = BalanceHours[LandscapeSubjectType];

					var tes = trs + parseFloat(SubjectCreditHours);
					AddHours[LandscapeSubjectType] = AddHours[LandscapeSubjectType] + tes;
					var ads = 'ad'+LandscapeSubjectType;
					dojo.byId(ads).value = AddHours[LandscapeSubjectType];

					//console.log(BalanceHours[LandscapeSubjectType]);

					var trow=document.getElementById('hor1').insertRow(rowid1);
					var tcol1=trow.insertCell(count);count++;
					var tcol2=trow.insertCell(count);count++;
					var tcol3=trow.insertCell(count);count++;
					var tcol4=trow.insertCell(count);count++;
					var tcol5=trow.insertCell(count);count++;
					var tcol6=trow.insertCell(count);count++;

					
					tcol1.innerHTML="<input type='hidden' value='"+IdSemester+"' name=IdSemestergrid[]>"+IdSemestername;
                                        tcol2.innerHTML="<input type='hidden' value='"+LandscapeSubjectType+"' name=LandscapeSubjectTypegrid[]>"+LandscapeSubjectTypename;
					tcol3.innerHTML="<input type='hidden' value='"+IdSubject+"' name=IdSubjectgrid[]>"+IdSubjectname;
                                        tcol4.innerHTML="<input type='hidden' value='"+IdProgramMajoring+"' name=IdProgramMajoringgrid[]>"+IdProgramMajoringname;
					tcol5.innerHTML="<input type='hidden' value='"+SubjectCreditHours+"' name=LandscapeCreditHoursgrid[]>"+SubjectCreditHours;
					//tcol6.innerHTML="<a href='#' onClick='deleteRowsubject(this,"+LandscapeSubjectType+","+SubjectCreditHours+"); return false;'><img src='<?php echo $this->baseUrl();?>/images/delete.png'  border=0 width='16' height='16'></a>";
					tcol6.innerHTML='<a href="#" onClick="deleteRowsubject(this,'+LandscapeSubjectType+','+SubjectCreditHours+',\''+IdSubjectname+'\',\''+LandscapeSubjectTypename+'\'); return false;"><img src="<?php echo $this->baseUrl();?>/images/delete.png"  border=0 width=16 height=16></a>';
                                        rowid1++;

					dojo.byId('subcredithours').value = '';
					//dijit.byId('IdSemester').set('value','');
					//dijit.byId('IdSemester').set('placeHolder','Select');
					dijit.byId('IdSubject').set('value','');
					dijit.byId('IdSubject').set('placeHolder','Select');
					document.getElementById('chours').innerHTML = '';
			    }
			}
		    else
		    {
				dojo.byId('subcredithours').value = '';
				//dijit.byId('IdSemester').set('value','');
				//dijit.byId('IdSemester').set('placeHolder','Select');
				dijit.byId('IdSubject').set('value','');
				dijit.byId('IdSubject').set('placeHolder','Select');
				document.getElementById('chours').innerHTML = '';
                                LSubCreditH[LandscapeSubjectType] = LSubCreditH[LandscapeSubjectType]- parseFloat(SubjectCreditHours);
				alert("Course Credit Hours Exceeds Course Type Credit Hours ");
				
	   		}
	}


	function deleteRowsubject(r,LType,SubCrHr,IdSubjectname,LandscapeSubjectTypename) {
		var dStat = confirm("Are you sure to delete?");
        if(dStat == true){
		rowid1--;
		var i=r.parentNode.parentNode.rowIndex;
		subjArray.splice(parseInt(i-1),1);
		document.getElementById('hor1').deleteRow(i);
		//LSubCreditH[LType] =  parseFloat(SubCrHr);
		LSubCreditH[LType] = LSubCreditH[LType]- parseFloat(SubCrHr);
		BalanceHourse = BalanceHours[LType] + parseFloat(SubCrHr);
		BalanceHours[LType] = BalanceHourse;
		var idS = 'id'+LType;
		dojo.byId(idS).value = BalanceHours[LType];

		var tes = trs + parseFloat(SubCrHr);
		AddHours[LType] = AddHours[LType] - tes;
		var ads = 'ad'+LType;
		dojo.byId(ads).value = AddHours[LType];
                
                var makeArr = IdSubjectname+'#'+LandscapeSubjectTypename;
                courseDataAndTypeArray.splice(courseDataAndTypeArray.indexOf(makeArr), 1);

		dojo.byId('subcredithours').value = '';
		//dijit.byId('IdSemester').set('value','');
		//dijit.byId('IdSemester').set('placeHolder','Select');
		dijit.byId('IdSubject').set('value','');
		dijit.byId('IdSubject').set('placeHolder','Select');
		document.getElementById('chours').innerHTML = '';
		} else {  }
	}

	function showtable() {
		dojo.byId("table1").style.display = "block";
		var Blockcount = dijit.byId('Blockcount').value;
		fnGetLevelList(Blockcount);
	}

	function addBlockDetails() {
		var flag = true;

		var block = dijit.byId("block");
		if(block.get('value')== "")
		{
			block.set('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}

		if(dijit.byId("blockname").value == ''){
		    dijit.byId("blockname").attr('required','true');
			dijit.byId("blockname").focus();flag = false;
		}

		if(flag == true) {
			blocknameInsert();
		}
		return flag;
	}

	var blockArray  = new Array();

	function blocknameInsert() {
		var block = dijit.byId("block");
		var blocknameid = dijit.byId("block").displayedValue;
		var blockname = dijit.byId("blockname").value;
		blockArray.push(blocknameid);
		if(arrHasDupes(blockArray)) {
			blockArray = blockArray.unique();
			alert("Duplicate Block");
		} else {
			var trow=document.getElementById('hor5').insertRow(rowid3);
			var tcol1=trow.insertCell(0);
			var tcol2=trow.insertCell(1);
			var tcol3=trow.insertCell(2);

			tcol1.innerHTML="<input type='hidden'   value='"+block+"' name=blockgrid[]>"+blocknameid;
			tcol2.innerHTML="<input type='hidden'  value='"+blockname+"' name=blocknamegrid[]>"+blockname;
			tcol3.innerHTML="<a href='#' onClick='deletelevel(this); return false;'><img src='<?php echo $this->baseUrl();?>/images/delete.png'  border=0 width='16' height='16'></a>";
			rowid3++;

	}
	}

	function deletelevel(r) {
	    var dStat = confirm("Are you sure to delete?");
        if(dStat == true){
		rowid3--;
		var i=r.parentNode.parentNode.rowIndex;
		blockArray.splice(parseInt(i-1),1);
		document.getElementById('hor5').deleteRow(i);
		} else { }
	}

	function fngetblockname() {
		var block = dijit.byId('block').displayedValue;
		dijit.byId('blockname').set('value','Block'+block);

	}

	function showblocksub(){
		dojo.byId("table5").style.display = "block";
		var Blockcount = dijit.byId('Blockcount').value;
		 fnGetBlocksub(Blockcount);
		 dijit.byId('subjectblock').set('value','');
		 dijit.byId('subjectblock').set('placeHolder','Select');
                
                 
	}

	function addBlockyearDetails() {
		var flag = true;
		if(dijit.byId("Year")==''){
		    dijit.byId("Year").attr('required','true');
			dijit.byId("Year").focus();flag = false;
		}
		var blocksub = dijit.byId("Year");
		if(blocksub.get('value')== "")
		{
			blocksub('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}

		if(dijit.byId("YearSemester")==''){
		    dijit.byId("YearSemester").attr('required','true');
			dijit.byId("YearSemester").focus();flag = false;
		}
		var subjectblock = dijit.byId("YearSemester");
		if(subjectblock.get('value')== "")
		{
			subjectblock('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}

		if(flag == true) {
			LandscapeblockyearInsert();
		}
		return flag;
	}

	function LandscapeblockyearInsert() {
		var count = 0;
		var year = dijit.byId("Year");
		var yearname = dijit.byId("Year").displayedValue;

		var yearsemester = dijit.byId("YearSemester");
		var yearsemestername = dijit.byId("YearSemester").displayedValue;

		var trow=document.getElementById('hor10').insertRow(rowid5);
		var tcol1=trow.insertCell(count);count++;
		var tcol2=trow.insertCell(count);count++;
		var tcol3=trow.insertCell(count);count++;
		tcol1.innerHTML="<input type='hidden'   value='"+year+"' name=blockyeargrid[]>"+yearname;
		tcol2.innerHTML="<input type='hidden' value='"+yearsemester+"' name=yearblocksemgrid[]>"+yearsemestername;
		tcol3.innerHTML="<a href='#' onClick='deleteblockyear(this); return false;'><img src='<?php echo $this->baseUrl();?>/images/delete.png'  border=0 width='16' height='16'></a>";
		rowid5++;

	}

	function deleteblockyear(r)
	{
		var dStat = confirm("Are you sure to delete?");
        if(dStat == true){
		rowid5--;
		var i=r.parentNode.parentNode.rowIndex;
		subjectArray.splice(parseInt(i-1),1);
		document.getElementById('hor10').deleteRow(i);
		} else { }


	}
	//////

	function addBlockSubDetails() {
		var flag = true;
		if(dijit.byId("blocksub")==''){
		    dijit.byId("blocksub").attr('required','true');
			dijit.byId("blocksub").focus();flag = false;
		}
		var blocksub = dijit.byId("blocksub");
		if(blocksub.get('value')== "")
		{
			blocksub('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}

		if(dijit.byId("subjectblock")==''){
		    dijit.byId("subjectblock").attr('required','true');
			dijit.byId("subjectblock").focus();flag = false;
		}
		var subjectblock = dijit.byId("subjectblock");
		if(subjectblock.get('value')== "")
		{
			subjectblock('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}
		if(dijit.byId("CourseType")==''){
		    dijit.byId("CourseType").attr('required','true');
			dijit.byId("CourseType").focus();flag = false;
		}
		var coursetype = dijit.byId("CourseType");
		if(coursetype.get('value')== "")
		{
			coursetype('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}

		if(flag == true) {
			LandscapeblocksubjectInsert();
		}
		return flag;
	}

	function LandscapeblocksubjectInsert() {
		var count = 0;
		var blocksub = dijit.byId("blocksub");
		var blocksubname = dijit.byId("blocksub").displayedValue;

		var subjectblock = dijit.byId("subjectblock");
		var subjectblockname = dijit.byId("subjectblock").displayedValue;

		var coursetype = dijit.byId("CourseType");
		var coursetypename = dijit.byId("CourseType").displayedValue;

		var trow=document.getElementById('hor6').insertRow(rowid4);
		var tcol1=trow.insertCell(count);count++;
		var tcol2=trow.insertCell(count);count++;
		var tcol3=trow.insertCell(count);count++;
		var tcol4=trow.insertCell(count);count++;
		tcol1.innerHTML="<input type='hidden'   value='"+blocksub+"' name=blocksubnamegrid[]>"+blocksubname;
		tcol2.innerHTML="<input type='hidden' value='"+subjectblock+"' name=subjectblocknamegrid[]>"+subjectblockname;
		tcol3.innerHTML="<input type='hidden'   value='"+coursetype+"' name=coursetypegrid[]>"+coursetypename;
		tcol4.innerHTML="<a href='#' onClick='deleteblocksubject(this); return false;'><img src='<?php echo $this->baseUrl();?>/images/delete.png'  border=0 width='16' height='16'></a>";
		rowid4++;

	}

	function showtablesmester() {
		dojo.byId("table3").style.display = "block";
		dojo.byId("table4").style.display = "block";
		var Blockcount = dijit.byId('Blockcount').value;
		var SemsterCount = dijit.byId('SemsterCount').value;
		fnGetBlocksemList(Blockcount);
		fnGetSemesterList(SemsterCount);

	}

	function addBlockSemDetails() {
		var flag = true;
		if(dijit.byId("BlockDtlsList")==''){
		    dijit.byId("BlockDtlsList").attr('required','true');
			dijit.byId("BlockDtlsList").focus();flag = false;
		}
		var BlockDtlsList = dijit.byId("BlockDtlsList");
		if(BlockDtlsList.get('value')== "")
		{
			BlockDtlsList('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}

		if(dijit.byId("SemNameList")==''){
		    dijit.byId("SemNameList").attr('required','true');
			dijit.byId("SemNameList").focus();flag = false;
		}
		var SemNameList = dijit.byId("BlockDtlsList");
		if(SemNameList.get('value')== "")
		{
			SemNameList('class','dijitTextBoxError dijitComboBoxError');
			flag = false;
		}

		if(flag == true) {
			LandscapeblocksemesterInsert();
		}
		return flag;
	}
	var subjectArray  = new Array();

	function LandscapeblocksemesterInsert() {
		var count = 0;
		var BlockDtlsList = dijit.byId("BlockDtlsList");
		var BlockDtlsListname = dijit.byId("BlockDtlsList").displayedValue;

		var SemNameList = dijit.byId("SemNameList");
		var SemNameListname = dijit.byId("SemNameList").displayedValue;

		var trow=document.getElementById('hor3').insertRow(rowid2);
		var tcol1=trow.insertCell(count);count++;
		var tcol2=trow.insertCell(count);count++;
		var tcol3=trow.insertCell(count);count++;
		tcol1.innerHTML="<input type='hidden'   value='"+SemNameListname+"' name=SemNameListnamegrid[]>"+SemNameListname;
		tcol2.innerHTML="<input type='hidden' value='"+BlockDtlsList+"' name=BlockDtlsListgrid[]>"+BlockDtlsListname;
		tcol3.innerHTML="<a href='#' onClick='deleteblocksubject(this); return false;'><img src='<?php echo $this->baseUrl();?>/images/delete.png'  border=0 width='16' height='16'></a>";
		rowid2++;

	}

	function deleteblocksubject(r)
	{
		var dStat = confirm("Are you sure to delete?");
        if(dStat == true){
		rowid2--;
		var i=r.parentNode.parentNode.rowIndex;
		subjectArray.splice(parseInt(i-1),1);
		document.getElementById('hor3').deleteRow(i);
		} else { }


	}

	function arrHasDupes( A ) {              // finds any duplicate array elements using the fewest possible comparison
		var i, j, n;
		n=A.length;   						// to ensure the fewest possible comparisons
		for (i=0; i<n; i++) {                // outer loop uses each item i at 0 through n
			for (j=i+1; j<n; j++) {          // inner loop only compares items j at i+1 to n
				if (A[i]==A[j]) return true;
			}
		}
		return false;
	}

	Array.prototype.unique = function () {
	    var r = new Array();
	    o:for(var i = 0, n = this.length; i < n; i++) {
	        for(var x = 0, y = r.length; x < y; x++) {
	        	if(r[x]==this[i]) {
	                	continue o;
	              }
	        }
	        r[r.length] = this[i];
	    }
	    return r;
	}
	function showtableyear(){
		dojo.byId("table8").style.display = "block";
		var YearCount = dijit.byId('YearCount').value;
		var SemsterCount = dijit.byId('SemsterCount').value;
		yearlist(YearCount);
		semlist(SemsterCount);
	}
	function yearlist(YearCount){
		if(YearCount != "") {
			var xhrArgs = {
				url: "<?php echo $this->baseUrl();?>"+"/generalsetup/landscape/getyearlist/YearCount/"+YearCount,
				handleAs:'json',
				load:function(data){
					//console.log(data);
					AutoFillNextEditableDropDown("Year",data);
				}
			}
			dojo.xhrGet(xhrArgs);
		}
	}
	function semlist(YearCount){
		if(YearCount != "") {
			var xhrArgs = {
				url: "<?php echo $this->baseUrl();?>"+"/generalsetup/landscape/getyearlist/YearCount/"+YearCount,
				handleAs:'json',
				load:function(data){
					//console.log(data);
					AutoFillNextEditableDropDown("YearSemester",data);
				}
			}
			dojo.xhrGet(xhrArgs);
		}
	}
//-->
</script>
<fieldset>
	<legend>
		<?php echo $this->translate($this->Landscape);?>
	</legend>
	<Form dojoType="dijit.form.Form" id="myForm" action="" method="post"
		name="myForm">
		<script type="dojo/method" event="onSubmit">
                if (this.validate()) {
					if(dijit.byId('ProgramDescription').value == ''){
						alert("Please enter Landscape Description");
						dijit.byId("ProgramDescription").attr('required','true');
						dijit.byId("ProgramDescription").focus();
						return false;	
					}	
					return true;
                } else {
                    return false;
                }
			</script>
		<div>
			<table class="table" width="100%">
				<tr>
					<th colspan="4"><?php echo $this->translate("Block-Based Landscape");?>
					</th>
				</tr>

				<tr>
					<td><?php echo $this->translate("Program Name");?></td>
					<td><?php echo $this->program;?></td>
					<td><?php echo $this->translate("Total")." ".$this->translate("Credit")." ".$this->translate("Hours");?>
					</td>
					<td><?php echo $this->lobjlandscapeform->TotalCreditHours;?></td>

				</tr>
				<tr>
					<td><?php echo $this->translate("Scheme");?></td>
					<td><?php echo $this->lobjlandscapeform->Scheme;?></td>
					<td><?php echo $this->translate("Landscape Description");?><span
						class="reqMark">*</span></td>
					<td><?php echo $this->lobjlandscapeform->ProgramDescription;?></td>
				</tr>
				<tr>
					<td><?php echo $this->translate("Add/Drop");?></td>
					<td><?php echo $this->lobjlandscapeform->AddDrop;?></td>

					<td><?php echo $this->translate($this->defaultlanguage);?></td>
					<td><?php echo $this->lobjlandscapeform->landscapeDefaultLanguage;?>
					</td>

				</tr>
				<tr>
					<th colspan="4"><?php echo $this->translate($this->Landscape).' '.$this->translate("Details");?>
					</th>
				</tr>
				<tr>
					<td><?php echo $this->translate($this->Landscape);?><span
						class="reqMark">*</span></td>
					<td><?php echo $this->lobjlandscapeform->LandscapeType;?> <?php echo $this->lobjlandscapeform->UpdDate;?>
						<?php echo $this->lobjlandscapeform->UpdUser;?> <?php echo $this->lobjlandscapeform->IdProgram;?>
					</td>
					<td><?php echo $this->translate("No").' '.$this->translate("of").' '.$this->translate("Blocks");?>
					</td>
					<td><?php echo $this->lobjlandscapeform->Blockcount;?></td>
				</tr>
				<tr>
					<td><?php echo $this->translate("Intake");?><span class="reqMark"></span>
					</td>
					<td><?php echo $this->lobjlandscapeform->IdStartSemester;?></td>
					<td><?php echo $this->translate("No").' '.$this->translate("of").' '.$this->translate("Semester");?>
					</td>
					<td><?php echo $this->lobjlandscapeform->SemsterCount;?> <?php echo $this->lobjlandscapeform->session_id;?>
					</td>
				</tr>
				<tr>
					<td><?php echo $this->translate("Active");?><span class="reqMark"></span>
					</td>
					<td><?php echo $this->lobjlandscapeform->Active;?></td>
					<td><?php echo $this->translate("No of Year");?><span
						class="reqMark"></span></td>
					<td><?php echo $this->lobjlandscapeform->YearCount;?></td>
				</tr>
				<tr id="tr1">
					<td colspan=4 align="right"><?php echo $this->lobjlandscapeform->Add9;?>
					</td>
				</tr>
			</table>
		</div>
		<div id="prgreq" style="display: none">
			<table class="table" width="100%">
				<tr>
					<th colspan="4"><?php echo $this->translate("Program").' '.$this->translate("Requirement");?>
					</th>
				</tr>
				<tr>
					<td><?php echo $this->translate("Subject");?> <?php echo $this->translate("Type");?><span
						class="reqMark"></span></td>
					<td><?php echo $this->lobjlandscapeform->SubjectType;?></td>
					<td><?php echo $this->translate("Balance");?></td>
					<td><?php echo $this->lobjlandscapeform->Balance;?></td>
				</tr>
				<tr>
					<td><?php echo $this->translate("Credit");?> <?php echo $this->translate("Hours");?><span
						class="reqMark"></span></td>
					<td><?php echo $this->lobjlandscapeform->CreditHours;?></td>
					<td></td>
					<td></td>
				</tr>
				<tr>
					<td colspan=4 align="right"><?php echo $this->lobjlandscapeform->Add;?>
					</td>
				</tr>
			</table>
			<table id="horprg" class="table" width="100%">
				<tr>
					<th><?php echo $this->translate->_("Subject").' '.$this->translate->_("Type")?>
					</th>
					<th><?php echo $this->translate->_("Credit").' '.$this->translate->_("Hours")?>
					</th>
					<th><?php echo $this->translate->_("Balance").' '.$this->translate->_("Hours")?>
					</th>
					<th><?php echo $this->translate->_("Added").' '.$this->translate->_("Hours")?>
					</th>
					<th><?php echo $this->translate->_("Delete")?></th>
				</tr>
				<tr>
					<td colspan=5 id="tr2" align="right"><?php echo $this->lobjlandscapeform->Add7;?>
					</td>
				</tr>
			</table>
		</div>
		<div id="table2" style="display: none">
			<table class="table" width="100%">
				<tr>
					<th colspan="4"><?php echo $this->translate("Subject").' '.$this->translate("Details");?>
					</th>
				</tr>

				<tr>
					<td><?php echo $this->translate("Semester");?><span class="reqMark">*</span>
					</td>
					<td><?php echo $this->lobjlandscapeform->IdSemester;?></td>
					<td><?php echo $this->translate("Subject").' '.$this->translate("Type");?><span
						class="reqMark">*</span></td>
					<td><?php echo $this->lobjlandscapeform->LandscapeSubjectType;?></td>
				</tr>

				<tr>
					<td><?php echo $this->translate("Subject");?><span class="reqMark">*</span>
					</td>
					<td><?php echo $this->lobjlandscapeform->IdSubject;?><input
						type="hidden" name="subcredithours" id="subcredithours" value="" />
					</td>
					<td><?php echo $this->translate("Majoring");?></td>
					<td><?php echo $this->lobjlandscapeform->IdProgramMajoring;?></td>
				</tr>

				<tr>
					<td><?php echo $this->translate("Credit").' '.$this->translate("Hours");?>
					</td>
					<td><span id='chours'></span></td>
					<td><?php echo $this->translate("Compulsory");?><span
						class="reqMark"></span></td>
					<td><?php echo $this->lobjlandscapeform->Compulsory;?></td>
				</tr>



				<tr>
					<td colspan=4 align="right"><?php echo $this->lobjlandscapeform->Add1;?><input
						type="hidden" name="IdProgramReq"
						value="<?php echo $this->IdProgramReq;?>" />
					</td>
				</tr>
			</table>
			<table id="hor1" class="table" width="100%">
				<tr>

					<th><?php echo $this->translate->_("Semester");?></th>
					<th><?php echo $this->translate->_("Subject").' '.$this->translate->_("Type");?>
					</th>
					<th><?php echo $this->translate->_("Subject");?></th>
					<th><?php echo $this->translate->_("Majoring");?></th>
					<th><?php echo $this->translate->_("Credit").' '.$this->translate->_("Hours");?>
					</th>
					<th><?php echo $this->translate->_("Delete")?></th>
				</tr>
				<tr>
					<td colspan=6 id="tr2" align="right"><?php echo $this->lobjlandscapeform->Add6;?>
					</td>
				</tr>
			</table>
		</div>
		<div id="table1" style="display: none">
			<table class="table" width="100%">
				<tr>
					<th colspan="4"><?php echo $this->translate("Define").' '.$this->translate("Block Name");?>
					</th>
				</tr>
				<tr>
					<td><?php echo $this->translate("Block").' '.$this->translate("Number");?><span
						class="reqMark"></span></td>
					<td><?php echo $this->lobjlandscapeform->block;?> <?php echo $this->lobjlandscapeform->idlandscapetemp;?>
					</td>
					<td><?php echo $this->translate("Block").' '.$this->translate("Name");?>
					</td>
					<td><?php echo $this->lobjlandscapeform->blockname;?> <?php echo $this->lobjlandscapeform->idlandscapeblockid;?>
					</td>
				</tr>
				<tr>
					<td colspan="4" align="right"><?php echo $this->lobjlandscapeform->Add3;?>
					</td>
				</tr>
			</table>
			<table id="hor5" class="table" width="100%">
				<tr>
					<th><?php echo $this->translate->_("Block");?></th>
					<th><?php echo $this->translate->_("Block").' '.$this->translate->_("Name");?>
					</th>
					<th><?php echo $this->translate->_("Delete")?></th>
				</tr>
				<tr id="tr2">
					<td colspan="4" align="right"><?php echo $this->lobjlandscapeform->Add8;?>
					</td>
				</tr>
			</table>
		</div>


		<div id="table5" style="display: none">
			<table class="table" width="100%">
				<tr>
					<th colspan="4"><?php echo $this->translate->_("Block").' '.$this->translate->_("Subject").' '.$this->translate->_("Details");?>
					</th>
				</tr>
				<tr>
					<td><?php echo $this->translate("Block");?></td>
					<td><?php echo $this->lobjlandscapeform->blocksub;?></td>
					<td><?php echo $this->translate("Subject").' '.$this->translate->_("Name");?>
					</td>
					<td><?php echo $this->lobjlandscapeform->subjectblock;?></td>
				</tr>
				<tr>
					<td><?php echo $this->translate("$this->Subject").' '.$this->translate("Type");?>
					</td>
					<td><?php echo $this->lobjlandscapeform->CourseType;?></td>
				</tr>
				<tr>
					<td colspan=4 align="right"><?php echo $this->lobjlandscapeform->Add10;?>
					</td>
				</tr>
			</table>
			<table id="hor6" class="table" width="100%">
				<tr>
					<th><?php echo $this->translate->_("Block");?></th>
					<th><?php echo $this->translate->_("Subject").' '.$this->translate->_("Name");?>
					</th>
					<th><?php echo $this->translate("Course Type");?></th>
					<th><?php echo $this->translate->_("Delete")?></th>

				</tr>
				<tr>
					<td colspan=5 id="tr6" align="right"><?php echo $this->lobjlandscapeform->Add11;?>
					</td>
				</tr>
			</table>
		</div>
		<div id="table3" style="display: none">
			<table class="table" width="100%">
				<tr>
					<th colspan="4"><?php echo $this->translate->_("Block").' '.$this->translate->_("Semester").' '.$this->translate->_("Details");?>
					</th>
				</tr>
				<tr>
					<td><?php echo $this->translate("Semester");?></td>
					<td><?php echo $this->lobjlandscapeform->SemNameList;?></td>
					<td><?php echo $this->translate("Block");?></td>
					<td><?php echo $this->lobjlandscapeform->BlockDtlsList;?> <?php echo $this->lobjlandscapeform->IdLandscapetempblocksubject;?>
					</td>
				</tr>
				<tr>
					<td colspan=4 align="right"><?php echo $this->lobjlandscapeform->Add5;?>
					</td>
				</tr>
			</table>
			<table id="hor3" class="table" width="100%">
				<tr>
					<th><?php echo $this->translate->_("Semester");?></th>
					<th><?php echo $this->translate->_("Block").' '.$this->translate->_("Name");?>
					</th>
					<th><?php echo $this->translate->_("Delete")?></th>
				</tr>
				<tr>
					<td colspan=4 align="right"><?php echo $this->lobjlandscapeform->Add13;?>
					</td>
				</tr>
			</table>
		</div>

		<div id="table8" style="display: none">
			<table class="table" width="100%">
				<tr>
					<th colspan="4"><?php echo $this->translate->_("Year").' '.$this->translate->_("Semester").' '.$this->translate->_("Details");?>
					</th>
				</tr>
				<tr>
					<td><?php echo $this->translate("Year");?></td>
					<td><?php echo $this->lobjlandscapeform->Year;?></td>
					<td><?php echo $this->translate("Semester");?></td>
					<td><?php echo $this->lobjlandscapeform->YearSemester;?> <?php echo $this->lobjlandscapeform->IdLandscapetempblockyearsemester;?>
					</td>
				</tr>
				<tr>
					<td colspan=4 align="right"><?php echo $this->lobjlandscapeform->Add12;?>
					</td>
				</tr>
			</table>
			<table id="hor10" class="table" width="100%">
				<tr>
					<th><?php echo $this->translate->_("Year");?></th>
					<th><?php echo $this->translate->_("Semester");?></th>
					<th><?php echo $this->translate->_("Delete")?></th>
				</tr>
			</table>
		</div>

		<div id="table4">
			<table class="table" width="100%">
				<tr align="right">
					<td><?php echo $this->lobjlandscapeform->Save;?></td>
				</tr>
			</table>
		</div>
		<div>
			<table class="table" width="100%">
				<tr align="right">
					<td><input type="button" class="NormalBtn"
						dojotype="dijit.form.Button"
						label="<?php echo $this->translate("Back"); ?>"
						onclick="window.location.href='<?php echo $this->url(array('module'=>'generalsetup','controller'=>'landscape', 'action'=>'addlandscape','id'=>$this->IdProgram),'default',true);?>';" />
					</td>
				</tr>
			</table>
		</div>


		<!-- BLOCk LANDSCAPE COPY   -->
		<div>

			<table class="table" width="100%">
				<tr>
					<th colspan="4"><?php echo $this->translate("Copy").' '.$this->translate("Landscape");?>
						<span id="targetCopy"
						style="color: red; display: none; margin-left: 405px;">Copying
							Data, Please Wait a While...</span>
					</th>
				</tr>


				<tr>
					<td><?php echo $this->translate("Program Name");?></td>
					<td><?php echo $this->program;?></td>
					<td><?php echo $this->translate("Scheme");?></td>
					<td><?php echo $this->lobjlandscapeform->CopyScheme;?></td>
				</tr>
				<tr>
					<td><?php echo $this->translate("Intake");?></td>
					<td><?php echo $this->lobjlandscapeform->CopyIdStartSemester;?></td>
					<td><?php echo $this->translate("Active");?></td>
					<td><?php echo $this->lobjlandscapeform->CopyActive;?></td>
				</tr>

				<tr>
					<td colspan="4"><?php echo $this->translate("Copy From");?></td>
				</tr>
				<tr>
					<td><?php echo $this->translate("Intake");?></td>
					<td><?php echo $this->lobjlandscapeform->CopyFromIdStartSemester;?>
					</td>
					<td><?php echo $this->translate("Scheme");?></td>
					<td><?php echo $this->lobjlandscapeform->CopyFromScheme;?></td>
				</tr>



			</table>
		</div>

		<div id="table44" class="table" style="float: right;">
			<table class="table" width="100%">
				<tr align="right">
					<input align="right" type="button" class="NormalBtn"
						onClick="copythirdlandscape();" dojotype="dijit.form.Button"
						label="<?php echo $this->translate("Copy"); ?>" />
				</tr>
			</table>
		</div>

		<!-- BLOCk LANDSCAPE COPY  ENDS  -->





	</Form>
</fieldset>
<script language="JavaScript" type="text/javascript">
function copythirdlandscape() {
$('#targetCopy').show();
var copyfrom_intakes = dijit.byId('CopyFromIdStartSemester').value;
var copyfrom_schemes = dijit.byId('CopyFromScheme').value;
var id_program = '<?php echo $this->IdProgram;?>';
var copy_schemes = dijit.byId('CopyScheme').value;
var copy_intake = dijit.byId('CopyIdStartSemester').value;
var copy_active = dijit.byId('CopyActive').value;

$.post("<?php echo $this->baseUrl();?>/generalsetup/landscape/copythirdlandscape", { copyfrom_intakes: copyfrom_intakes, copyfrom_schemes: copyfrom_schemes, id_program: id_program, copy_intake: copy_intake, copy_active: copy_active, copy_schemes: copy_schemes},
   function(data) {
     if(data=='done') {
     	window.location.href= "<?php echo $this->baseUrl();?>/generalsetup/landscape/addlandscape/id/<?php echo $this->IdProgram;?>";
       }else {  
           $('#targetCopy').text('No Matching Landscape Found');
           $('#targetCopy').show(); 
       }
   });


}
</script>



