<fieldset>
	<legend><?php echo $this->translate("Penjadwalan Audit")?></legend>
		<form method="post" id="form" name="form">
			<input type="hidden" name="id" id="id" value="">
			<table width="100%">
				<tr>
					<td>Tanggal Mulai Audit :</td>
					<td><input type="date" name="mulai_audit" required></td>
				</tr>
				<tr>
					<td>Audit (Unit Kerja) :</td>
					<td>
						<select name="unit" style="resize:none;width:144px;height:25px">
							<option label="Pilih Unit Kerja">
							<?php foreach ($this->unitkerja as $unit) { ?>
							<option value="<?php echo $unit['unit_id']; ?>" 
									label="<?php echo $unit['nama_unit'] ?> (<?php echo $unit['kd_unit']?>)">
							<?php } ?>
						</select>
					</td>
				</tr>
				<tr>
					<td>Tanggal Notifikasi :</td>
					<td><input type="date" name="notif" required></td>
				</tr>
				<tr>
					<td>Tanggal Kirim Checklist :</td>
					<td><input type="date" name="kirim_cheklist" required></td>
					<td>Tanggal Validasi Temuan Audit : </td>
					<td><input type="date" name="val_temuan_audit" required></td>
				</tr>
				<tr>
					<td>Tanggal Kumpul Checklist :</td>
					<td><input type="date" name="kumpul_cheklist" required></td>
					<td>Tanggal Validasi Rekomendasi TPP :</td>
					<td><input type="date" name="val_rekomendasi" required></td>
				</tr>
				<tr>
					<td>Tanggal Visitasi :</td>
					<td><input type="date" name="visitasi" required></td>
					<td>Tanggal Validasi Verifikasi TPP :</td>
					<td><input type="date" name="val_verivikasi" required></td>
				</tr>
				<tr>
					<td colspan="4" align="center">
					<input type="submit" name="Save" value="Save"></td>
				</tr>
					<table width="100%" class="table">
						<tr>
							<th width="20%">Tanggal Mulai Audit</th>
							<th width="40%">Audit</th>
							<th width="20%"></th>
							<th width="20%">Action</th>
						</tr>
						<?php 
                    		foreach ($this->penjadwal as $value) {
                    	?>
						<tr>
							<td><?php echo date('d-m-Y', strtotime($value['tgl_mulai_audit'])); ?></td>
							<td><?php echo $value['nama_unit'];?></td>
							<td><a href="<?php echo $this->baseUrl();?>/perencanaanaudit/penjadwalan-audit/timpelaksana/id/">Tim Pelaksana Audit</a></td>
							<td><a href="<?php echo $this->baseUrl();?>/perencanaanaudit/penjadwalan-audit/edit/id/<?php echo $value['kd_penjadwalan_audit'];?>">Edit</a>
							<a href="#">Delete</a></td>
						</tr>
						<?php }
						?>
					</table>
			</table>
		</form>
</fieldset>