<fieldset>
	<table>
		<tr>
			<td><button type="button">Penjadwalan Audit</button>
			<button type="button">Tim Pelaksanaan Audit</button></td>
		</tr>
        	
        		<form action="">
        			<table width="100%">
        			<legend><?php echo $this->translate("Penjadwalan Audit")?></legend>
        				<tr>
        					<td>Tanggal Mulai Audit :</td>
        					<td><input type="text"></td>
        					<td>Tanggal Validasi Temuan Audit :</td>
        					<td><input type="text"></td>
        				</tr>
        				<tr>
        					<td>Tanggal Mulai Audit :</td>
        					<td>
        						<select>
        							<option>Text Goes Here</option>
        						</select>
        					</td>
        					<td>Tanggal Validasi Rekomendasi TPP :</td>
        					<td><input type="text"></td>
        				</tr>
        				<tr>
        					<td>Tanggal Kirim Checklist :</td>
        					<td><input type="text"></td>
        					<td>Tanggal Validasi Verifikasi TPP :</td>
        					<td><input type="text"></td>
        				</tr>
        				<tr>
        					<td>Tanggal Kumpul Cheklist :</td>
        					<td><input type="text"></td>
        				</tr>
        				<tr>
        					<td>Tanggal Visitasi :</td>
        					<td><input type="text"></td>
        				</tr>
        				<tr>
        					<td colspan="4" align="center">
        					<input type="submit" name="Save" value="Save"></td>
        				</tr>
        			</table>
        		</form>
		</table>
</fieldset>