<fieldset>
    <legend><?php echo $this->translate("Tim Pelaksana Auditor")?></legend>
        <form action="">
        	<table width="100%">
    			<tr>
    				<td>Tanggal Mulai Audit : </td>
    				<td><?php echo a ?></td>
    			</tr>
    			<tr>
    				<td>Auditi :</td>
    				<td><?php echo a ?></td>
    			</tr>
        		<tr>
        			<td>Auditor :</td>
        			<td>
        				<select name="auditor" style="resize:none;width:144px;height:25px">
        					<option label="Pilih Auditor">
        					
        				</select>
        			</td>
        		</tr>
        		<tr>
        			<td colspan="2" align="center">
        			<input type="submit" name="Save" value="Save"></td>
        		</tr>
        			<table width="100%" class="table">
        				<tr>
        					<th>Auditor</th>
        					<th>Action</th>
        				</tr>
        			</table>
        	</table>
        </form>
</fieldset>