<script type="text/javascript">

	dojo.addOnLoad(function() {
                <?php if(!isset($_POST['Save'])){ ?>
		dijit.byId('IdSemester').set('value','');
		dijit.byId('IdSemester').set('placeHolder','Select');
                dijit.byId('IdActivity').set('value','');
		dijit.byId('IdActivity').set('placeHolder','Select');
              <?php } ?>
	});
</script>
<fieldset>
  <legend><?php echo $this->translate("Calender");?></legend>
  <form dojoType="dijit.form.Form"  id="company_form" name="company_form" action="" method="post">
    <script type="dojo/method" event="onSubmit">
      if (this.validate()) {
        return true;
      } else {
        return false;
      }
    </script>
    <table class="table" width="100%" >
      <tr>
        <th colspan = "4"><?php echo $this->translate("Calender").' '.$this->translate("Details");?></th>
      </tr>
      <tr>
        <td><?php echo $this->translate("Semester");?><span class="reqMark">*</span></td>
        <td><?php echo $this->lobjsemestercalenderForm->IdSemester;?>
      </tr>
      <tr>
        <td><?php echo $this->translate("Activity");?><span class="reqMark">*</span></td>
        <td><?php echo $this->lobjsemestercalenderForm->IdActivity;?>
      </tr>
      <tr>
        <td><?php echo $this->translate("Start Date");?><span class="reqMark">*</span></td>
	<td><?php echo $this->lobjsemestercalenderForm->StartDate;?></td>
      </tr>
      <tr>
        <td><?php echo $this->translate("End Date");?><span class="reqMark">*</span></td>
	<td><?php echo $this->lobjsemestercalenderForm->EndDate;?></td>
      </tr>
      <tr>
        <td colspan=4 align="right"><?php echo $this->lobjsemestercalenderForm->Save;?>
          <input type="button" class="NormalBtn" dojotype="dijit.form.Button"
            label="<?php echo $this->translate("Back"); ?>"
            onclick="window.location.href='<?php echo $this->url(array('module'=>'generalsetup','controller'=>'semestercalender', 'action'=>'index'),'default',true);?>';" />
	</td>
      </tr>
    </table>
  </form>
</fieldset>