<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="">
<head>

<script type="text/javascript">
	dojo.addOnLoad(function() {

		var cid = dijit.byId('Country').value;
		//fnGetCountryStateList(cid);
	});

function fnGetStateCityListofUniversity(idState){ 
		if(idState != "")
			{ var xhrArgs = {
						url: "<?php echo $this->baseUrl();?>"+"/generalsetup/user/getstatecitylist/idState/"+idState,
						handleAs:'json',
						load:function(data){ 
							AutoFillNextEditableDropDown("City",data); 
						}
				   }
				dojo.xhrGet(xhrArgs); 
			} 
		} 		
	
function fnGetCountryStateList(idCountry){ 
	if(idCountry != "" || idCountry != undefined)
		{ 
			var xhrArgs = {
					url: "<?php echo $this->baseUrl();?>"+"/generalsetup/user/getcountrystateslist/idCountry/"+idCountry,
					handleAs:'json',
					load:function(data){ 
						AutoFillNextEditableDropDown("State",data); 
			
					}
			   }
			dojo.xhrGet(xhrArgs); 
		} 
	} 
function fnGetStaffList(IdStaff){ 
	if(IdStaff != "")
		{ 
			var xhrArgs = {
					url: "<?php echo $this->baseUrl();?>"+"/generalsetup/user/getstafflist/idStaff/"+IdStaff,
					handleAs:'json',
					load:function(data){ 
						dijit.byId('FromDate').set('value',data['JoiningDate']);
					}
			   }
			dojo.xhrGet(xhrArgs); 
		} 
	} 	
		
function AutoFillNextEditableDropDown(EditableDropDownId,JSONText){
	dijit.byId(EditableDropDownId).setValue("");
	var ddwidget = dijit.byId(EditableDropDownId);
	ddwidget.setAttribute('disabled', false);
    var options = {
					label:"name",
					identifier:"key",
					items:JSONText
				  };
    ddwidget.store = new dojo.data.ItemFileReadStore( { data: options } );
}



function checkphonefield(){

 var workphone = dijit.byId("Phone1").value;
 var workcountrycode = dijit.byId('Phone1countrycode').value;
 var workstatecode = dijit.byId('Phone1statecode').value;

 var homePhone = dijit.byId("Phone2").value;
 var homecountrycode = dijit.byId('Phone2countrycode').value;
 var homestatecode = dijit.byId('Phone2statecode').value;

 var fax = dijit.byId("Fax").value;
 var faxstatecode = dijit.byId('faxstatecode').value;
 var faxcountrycode = dijit.byId('faxcountrycode').value;

 if(faxcountrycode!=''){
   if(faxstatecode == ''){
    dijit.byId("faxstatecode").focus();
    alert('Incorrect Fax details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
    dijit.byId("faxstatecode").set( "state", "Error" );
    return false;
   }
   if(fax == ''){
     dijit.byId("Fax").focus();
    alert('Incorrect Fax details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
    dijit.byId("Fax").set( "state", "Error" );
    return false;
   }
 }

 if(faxstatecode!=''){
   if(faxcountrycode == ''){
    dijit.byId("faxcountrycode").focus();
    alert('Incorrect Fax details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
    dijit.byId("faxcountrycode").set( "state", "Error" );
    return false;
   }
   if(fax == ''){
     dijit.byId("Fax").focus();
    alert('Incorrect Fax details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
    dijit.byId("Fax").set( "state", "Error" );
    return false;
   }
 }
  if(fax != ''){
    var len = fax.length;
    if(len < 5){
      dijit.byId("Fax").focus();
      alert('Incorrect Fax details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
      dijit.byId("Fax").set( "state", "Error" );
      return false;
    }
    if(faxcountrycode == ''){
      dijit.byId("faxcountrycode").focus();
       alert('Incorrect Fax details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
      dijit.byId("faxcountrycode").set( "state", "Error" );
      return false;
    }
    if(faxstatecode == ''){
      alert('Incorrect Fax details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
      dijit.byId("faxstatecode").focus();
      dijit.byId("faxstatecode").set( "state", "Error" );
      return false;
    }
  }

 if(workcountrycode!=''){
   if(workstatecode == ''){
    dijit.byId("Phone1statecode").focus();
    alert('Incorrect Phone details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
    dijit.byId("Phone1statecode").set( "state", "Error" );
    return false;
   }
   if(workphone == ''){
     dijit.byId("Phone1").focus();
    alert('Incorrect Phone details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
    dijit.byId("Phone1").set( "state", "Error" );
    return false;
   }
 }

 if(workstatecode!=''){
   if(workcountrycode == ''){
    dijit.byId("Phone1countrycode").focus();
    alert('Incorrect Phone details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
    dijit.byId("Phone1countrycode").set( "state", "Error" );
    return false;
   }
   if(workphone == ''){
     dijit.byId("Phone1").focus();
    alert('Incorrect Phone details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
    dijit.byId("Phone1").set( "state", "Error" );
    return false;
   }
 }
  if(workphone != ''){
    var len = workphone.length;
    if(len < 5){
      dijit.byId("Phone1").focus();
      alert('Incorrect Phone details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
      dijit.byId("Phone1").set( "state", "Error" );
      return false;
    }
    if(workcountrycode == ''){
      dijit.byId("Phone1countrycode").focus();
       alert('Incorrect Phone details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
      dijit.byId("Phone1countrycode").set( "state", "Error" );
      return false;
    }
    if(workstatecode == ''){
      alert('Incorrect Phone details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
      dijit.byId("Phone1statecode").focus();
      dijit.byId("Phone1statecode").set( "state", "Error" );
      return false;
    }
  }

  if(homecountrycode!=''){
   if(homestatecode == ''){
    dijit.byId("Phone2statecode").focus();
    alert('Incorrect Phone details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
    dijit.byId("Phone2statecode").set( "state", "Error" );
    return false;
   }
   if(homePhone == ''){
     dijit.byId("Phone2").focus();
    alert('Incorrect Phone details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
    dijit.byId("Phone2").set( "state", "Error" );
    return false;
   }
 }

 if(homestatecode!=''){
   if(homecountrycode == ''){
    dijit.byId("Phone2countrycode").focus();
    alert('correct Phone details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
    dijit.byId("Phone2countrycode").set( "state", "Error" );
    return false;
   }
   if(homePhone == ''){
     dijit.byId("Phone2").focus();
    alert('Incorrect Phone details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
    dijit.byId("Phone2").set( "state", "Error" );
    return false;
   }
 }



  if(homePhone != ''){
    var len = homePhone.length;
    if(len < 5){
      dijit.byId("Phone2").focus();
      alert('Incorrect Phone details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
      dijit.byId("Phone2").set( "state", "Error" );
      return false;
    }
    if(homecountrycode == ''){
      dijit.byId("Phone2countrycode").focus();
      alert('Incorrect Phone details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
      dijit.byId("Phone2countrycode").set( "state", "Error" );
      return false;
    }
    if(homestatecode == ''){
      alert('Incorrect Phone details. Please fill Country Code (XXX)-State Code(XX)-Phone(XXXXXXXXX)');
      dijit.byId("Phone2statecode").focus();
      dijit.byId("Phone2statecode").set( "state", "Error" );
      return false;
    }
  }
  return true;
}

</script> 
</head>
<body class='claro'>
 <fieldset>
    <legend><?php echo $this->translate("University");?></legend>
                <Form dojoType="dijit.form.Form"  id="myForm" action="" method="post"  name= "myForm">
                <script type="dojo/method" event="onSubmit">
                if (this.validate()) {
                  if(checkphonefield()){
                    return true;
                  }else{
                    return false;
                  }
                } else {
                  return false;
                }
				</script>
                    <table class="table" width="100%" >
                        <tr>
                             <th colspan = "4"><?php echo $this->translate("University").' '.$this->translate("Details");?></th>
                        </tr>
                        <tr>
                            <td ><?php echo $this->translate("University").' '.$this->translate("Name");?><span class="reqMark">*</span></td>
                            <td ><?php echo $this->lobjuniversityForm->Univ_Name;?>
                            	<?php echo $this->lobjuniversityForm->UpdDate;?>
                            	<?php echo $this->lobjuniversityForm->UpdUser;?>
                            	<?php echo $this->lobjuniversityForm->IdUniversity;?></td>
                            <td><?php echo $this->translate($this->defaultlanguage);?><span class="reqMark"></span></td>
                            <td><?php echo $this->lobjuniversityForm->Univ_ArabicName;?></td>
                       
                        </tr>
                        <tr>
                            <td ><?php echo $this->translate("Short Name");?><span class="reqMark">*</span></td>
                            <td ><?php echo $this->lobjuniversityForm->ShortName;?></td>
                            <td ><?php echo $this->translate("EPSBED Code");?></td>
                            <td ><?php echo $this->lobjuniversityForm->Univ_code_EPSBED;?></td>
                        </tr>
                        
                        <tr>
                        	<th colspan = "4"><?php echo $this->translate("Address").' '.$this->translate("Details");?></th>
                        </tr>
                        <tr> 
                            <td ><?php echo $this->translate("Address 1");?><span class="reqMark">*</span></td>
                            <td ><?php echo $this->lobjuniversityForm->Add1;?></td>
                            <td ><?php echo $this->translate("Address 2");?></td>
                             <td ><?php echo $this->lobjuniversityForm->Add2;?>
                        </tr>
                        <tr> 
                            <td ><?php echo $this->translate("Country");?><span class="reqMark">*</span></td>
                            <td ><?php echo $this->lobjuniversityForm->Country;?></td>
                            <td ><?php echo $this->translate("State");?><span class="reqMark">*</span></td>
                            <td ><?php echo $this->lobjuniversityForm->State;?></td>
                        </tr>
                        <tr> 
                            <td ><?php echo $this->translate("City");?><span class="reqMark"></span></td>
                            <td ><?php echo $this->lobjuniversityForm->City;?></td>
                            <td ><?php echo $this->translate("Zip Code");?><span class="reqMark"></span></td>
                            <td ><?php echo $this->lobjuniversityForm->Zip;?></td>
                        </tr>
                        <tr> 
                            <td ><?php echo $this->translate("Phone 1");?><span class="reqMark"></span></td>
                            <td ><?php echo $this->lobjuniversityForm->Phone1countrycode;?><?php echo $this->lobjuniversityForm->Phone1statecode;?><?php echo $this->lobjuniversityForm->Phone1;?></td>
                            <td ><?php echo $this->translate("Phone 2");?><span class="reqMark"></span></td>
                            <td ><?php echo $this->lobjuniversityForm->Phone2countrycode;?><?php echo $this->lobjuniversityForm->Phone2statecode;?><?php echo $this->lobjuniversityForm->Phone2;?></td>
                        </tr>
                        <tr> 
                            <td ><?php echo $this->translate("Fax");?></td>
                            <td ><?php echo $this->lobjuniversityForm->faxcountrycode;?><?php echo $this->lobjuniversityForm->faxstatecode;?><?php echo $this->lobjuniversityForm->Fax;?></td>
                            <td ><?php echo $this->translate("Email");?><span class="reqMark">*</span></td>
                            <td ><?php echo $this->lobjuniversityForm->Email;?></td>
                        </tr>
                        <tr> 
                            <td ><?php echo $this->translate("Url");?><span class="reqMark">*</span></td>
                            <td ><?php echo $this->lobjuniversityForm->Url;?></td>
                            <td ></td>
                            <td ></td>
                        </tr>
                        <tr>
                          <th colspan = "4"><?php echo $this->translate($this->Registrar).' '.$this->translate("Details");?></th>
                        </tr>
                        <tr>
                            <td><?php echo $this->translate("Registrar");?><span class="reqMark">*</span></td>
                            <td><?php echo $this->lobjuniversityForm->IdStaff;?></td>
                            <td><?php echo $this->translate("Joining").' '.$this->translate("Date");?><span class="reqMark">*</span></td>
                        	<td><?php echo $this->lobjuniversityForm->FromDate;?></td>
                        </tr>
                        <tr>
                        	<td><?php echo $this->lobjuniversityForm->ToDate;?></td>
                        	<td></td>
                        </tr>	
                        <tr> 
                            <td><?php echo $this->translate("Active");?><span class="reqMark"></span></td>
                            <td><?php echo $this->lobjuniversityForm->Active;?></td>
                            <td colspan=2></td>
                        </tr>
                          
                        <tr>
                          <td></td>
                          <td></td>
                            <td></td>        
                            <td align = "right"><?php echo $this->lobjuniversityForm->Save;?>
							<input type="button" class="NormalBtn" dojotype="dijit.form.Button" label="<?php echo $this->translate("Back"); ?>" onclick="window.location.href='<?php echo $this->url(array('module'=>'generalsetup','controller'=>'university', 'action'=>'index'),'default',true);?>';" />	
                            </td> 
                               
                        </tr>
              </table>
            
            </Form>

</fieldset>
</body>
</html>