<head>
<script>
dojo.addOnLoad(function(){
	dijit.byId('field3').focus();
	dijit.byId('field5').set('value','<?php echo $this->field5Val;?>');
	dijit.byId('field5').set('placeHolder','Select');
	});
</script>
</head>
<body class="claro">
<div align="center" style="background: #fff;">
	<ul class="stepsmenu">
		<li class="second"><a href="/generalsetup/university">University</a></li>
		<li class="third"><a href="/generalsetup/collegemaster">Faculty</a></li>
	    <li class="fourth"><a href="/generalsetup/departmentmaster">Department</a></li>
    	<li class="fifth"><a href="/generalsetup/branchofficevenue/index/idbrc/1">Branch</a></li>										
	</ul>
</div>
<div style="clear:both"></div>
<div id="searchDiv">
	<fieldset>
	<legend><?php echo $this->translate($this->College).' '.$this->translate("Search");?></legend>
            <div class="search" style="margin-left:20px;">
                    <form action="<?php echo $this->baseUrl();?>/generalsetup/collegemaster/index/search/1" method="POST">
                            <table width="100%">
                                <tr>
                                    <td class="label"><?php echo $this->translate($this->College).' '.$this->translate("Name");?></td>
                                    <td ><?php echo $this->lobjform->field3;?></td>
                                    <td class="label"><?php echo $this->translate("Short Name");?></td>
                                    <td ><?php echo $this->lobjform->field2;?></td>
                                </tr>
                                <tr>
                                	<td class="label"><?php echo $this->translate("Affiliated").' '.$this->translate("To");?></td>
                                    <td ><?php echo $this->lobjform->field5;?></td>
                                	<td ><?php echo $this->translate("Email");?></td>
                  					<td ><?php echo $this->lobjform->field4;?></td>
                                </tr>
                                  <tr>
                                  	<td ><?php echo $this->defaultlanguage;?></td>
                                    <td ><?php echo $this->lobjform->field18;?></td>
                                	<td class="label"><?php echo $this->translate("Active");?></td>
                                    <td ><?php echo $this->lobjform->field7;?></td>
                                </tr>
                                <tr>
                                <td align = "center" colspan = "4">

											<?php echo $this->lobjform->Search;?>
											<input type="button" class="NormalBtn" dojotype="dijit.form.Button" label="<?php echo $this->translate("Add"); ?>" onclick="window.location.href='<?php echo $this->url(array('module'=>'generalsetup','controller'=>'collegemaster', 'action'=>'newcollege'),'default',true);?>';" />
											<?php echo $this->lobjform->Clear;?>
								</td>

                                </tr>
                        </table>
                    </form>
            </div>
    </fieldset>
    <br/>
	<fieldset>
		<table class="table" width="100%" cellpadding="5" cellspacing="1">

	    	<tr>
	        	<th><?php echo $this->translate($this->College).' '.$this->translate("Name");?></th>
	        	<th ><?php echo $this->defaultlanguage;?></th>
	       	    <th><?php echo $this->translate("Short Name");?></th>
	       	    
	       </tr>
	        <?php if (count($this->paginator)): ?>
	        <?php foreach ($this->paginator as $lobjcollegemaster ): ?>
	  		<tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next()?>">
	        	<td><a href="<?php echo $this->url(array('module'=>'generalsetup','controller'=>'collegemaster', 'action'=>'editcollege' , 'id'=>$lobjcollegemaster['IdCollege']),'default',true);?>" ><?php print_r($this->escape($lobjcollegemaster['CollegeName']));?></a></td>
	        	<td><?php echo $this->escape($lobjcollegemaster['ArabicName']);?></td>
	    	    <td><?php echo $this->escape($lobjcollegemaster['ShortName']);?></td>
	    	    <?php endforeach; ?>
	            <?php endif; ?>
			</tr>
	    	<tr>
	        	<td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->lobjpaginator,'Sliding',
	                                    '/partials/my_pagination_control.phtml'); ?></div></td>
   			</tr>
		</table>
	</fieldset>
</div>
</body>
</html>
